### ISSUE TITLE
Why newer versions of GStreamer are needed?

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#109]
> Gstreamer, Gstreamer Plugins Good, Gstreamer Plugins Bad and Gstreamer Python (Since version 1.4.3 Pulseeffects needs Gstreamer 1.12 or above)
Can you please explain why Gstreamer 1.12 or above is needed? 
I want to package PulseEffects for Ubuntu 16.04, and it has Gstreamer 1.10: https://packages.ubuntu.com/search?suite=xenial&section=all&arch=any&keywords=gstreamer&searchon=names
What will not work?

**Comment by wwmm** [comment]
Gstreamer 1.12 is needed to properly access the spectrum from python. The other functions will probably work in older versions but I can not tell for sure because I use Arch Linux and it moved to gstreamer 1.12 a few months ago.

If you do not use the spectrum just disable it in the menu and you are probably going to be fine
