### ISSUE TITLE
Ctrl+c/Ctrl+Z not handled

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#118]
PulseEffects does not properly handle Ctrl+C. I just cannot terminate it from the terminal when I run it in the terminal.
If I terminate it with Ctrl+Z, the processes remain in the system, the window of PulseEffects freezes and new instances of PulseEffects cannot be launched (maybe make a runtime check for existing instances?)

**Comment by mikhailnov** [comment]
oh, depending on how it is solved, a command line flag to terminate all PulseEffects instances will be nice as it will make scripting terminating it easier (I don't know how to terminate it via script at the moment, because kill -9 will not call reverting pulseaudio changes made when PulseEffects starts up)

**Comment by wwmm** [comment]
Only one instance can be run as all of them would try to create/use the same pulseaudios sink. What is happening here is something else. The GTK main loop is not being finished properly when pressing Ctrl+C because I did not implement that yet. I still have to learn how to do this. I will take a look before making a new release.

**Comment by wwmm** [comment]
Handling Ctrl+c is easier than I though it would be. `GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, 2, self.quit)` is enough

**Comment by wwmm** [comment]
I released version 3.0.7 with this change

**Comment by mikhailnov** [comment]
pulseaudio clodses, but does not clean pulseaudio changes (e.g. its sinks are not removed)

**Comment by mikhailnov** [comment]
it does, but one of two pulseffect's sinks remain
probably need to call Gio.SimpleAction.new('quit', None) by ctrl+c, but not self.quit

**Comment by wwmm** [comment]
That is what I do not understand. I have no sink left after Ctrl+c. Nothing in the output of `pactl list sinks` and nothing in pavucontrol window.

I do not see a reason why Gio.SimpleAction.new should be called instead of the `quit` method of Gio.Application [https://lazka.github.io/pgi-docs/Gio-2.0/classes/Application.html#Gio.Application.quit](https://lazka.github.io/pgi-docs/Gio-2.0/classes/Application.html#Gio.Application.quit).

**Comment by mikhailnov** [comment]
now I have 2 sinks left... the terminal output when closing by close button and ctrl+c is the same

**Comment by mikhailnov** [comment]
very strange... now I can't reproduce it, all sinks are removed. Will test it more.
