### ISSUE TITLE
No Preset dropdown also create preset not working 

### ISSUE THREAD

**Issue by shivshankar3578** [wwmm/pulseeffects#124]
there is not preset drop down also create preset plus button icon not working. also there is big black screen 
instead of equalizer wave. 
![image](https://user-images.githubusercontent.com/10707846/32990780-5945a4ba-cd55-11e7-9a88-5bfe31be12f0.png)

pulseeffects: 3.0.8
os: Manjaro (Arch)
gtk3 3.22.21-1
gnome-desktop 1:3.26.2-1
DE xfce4

**Comment by wwmm** [comment]
I think the problem here is lack of a first steps tutorial for new users. My bad but I still could not find time for this.

The presets menu shows presets created by the user. There is no preset builtin in PulseEffects. First type a name for the preset in the text field and then click on the plus button. This should add a preset.

Unless you run PulseEffects in service mode [https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options) it will not turn on all apps by default. You have to use the switch that is near the application volume shown in image you posted. Your switch is off. That is why you have a black screen.

**Comment by shivshankar3578** [comment]
oh ! i got it now. thanks it helps
