### ISSUE TITLE
Option to hide/change spectrum analyzer. Resize windows.

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#13]
Could you make an option to hide the spectrum analyzer and maybe add other new cool spectrum analyzers also( I like clementine nyanalyzer). And why can't I resize the windows? I would like to make it fit nicely with music player. Thanks.

**Comment by wwmm** [comment]
Hi

I will think about the possibility of adding an option to hide/show the spectrum... I am not sure if I really want this because the spectrum will still be calculated under the hoods despite not being shown to the user... 

I had no special reason to disable window resizing.  Do you want to resize the window to a larger or smaller size? As far as I could see in my tests resizing the window to sizes smaller than the current default size it is not possible. The labels, controls and level bars put a lower bound on window size.

**Comment by kevinsmia1939** [comment]
Not having smaller size is fine just want to adjust to fit nicely rather than getting in the way. I want to disable hode spectrum so I can have extraspace for my music player.

**Comment by wwmm** [comment]
Hi, I added the options you asked in the latest version (1.3.3)

**Comment by kevinsmia1939** [comment]
That was fast!!
