### ISSUE TITLE
Flatpak package doesn't load up

### ISSUE THREAD

**Issue by Mounium** [wwmm/pulseeffects#156]
Installing it via flatpak on NixOS, I can't seem to start the app from command line with `flatpak run com.github.wwmm.pulseeffects` with the error below, but there doesn't seem to be a problem starting it from the Gnome Software Center. 
I would not have opened this issue, but I've only now figured out that for some reason I can get it to work from within the software center, sorry for the inconvenience, although I don't quite now what command does the software center issue to start it up, it would be good to know.  

```
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 83, in do_startup
    self.sie = SinkInputEffects(self.pm)
  File "/app/lib/python3.5/site-packages/PulseEffects/sink_input_effects.py", line 26, in __init__
    EffectsBase.__init__(self, self.pm.default_sink_rate, self.settings)
  File "/app/lib/python3.5/site-packages/PulseEffects/effects_base.py", line 24, in __init__
    PipelineBase.__init__(self, sampling_rate)
  File "/app/lib/python3.5/site-packages/PulseEffects/pipeline_base.py", line 64, in __init__
    self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 185, in do_command_line
    self.do_activate()
  File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 169, in do_activate
    self.init_ui()
  File "/app/lib/python3.5/site-packages/PulseEffects/application.py", line 116, in init_ui
    self.sie.init_ui()
AttributeError: 'Application' object has no attribute 'sie'
```

**Comment by wwmm** [comment]
This error:

```
self.audio_src.set_property('volume', 1.0)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

is happening because PE could not find GStreamer pulsesrc plugin that is from gst-plugins-good package. @AsavarTzeth may know what NixOS is missing

**Comment by AsavarTzeth** [comment]
As far as I know it makes no difference how you launch a flatpak application. The only thing that comes to mind is that your shell environment might differ.

Dependencies are all included within the flatpak container, located under `/app`, or the *org.gnome.Platform//3.26* runtime, under `/usr`. @Mounium could you check a few things for me?
1. Is everything, including runtimes up-to-date, run `flatpak update` (**without su/sudo**)?
2. What is the output of `flatpak info com.github.wwmm.pulseeffects`?

If you want to dig around inside the container environment you can easily do so:
```
flatpak run --command=sh com.github.wwmm.pulseeffects//stable
```

**Comment by AsavarTzeth** [comment]
That is the latest commit at least. What version of flatpak are you using? (`flatpak --version`) I am guessing you are running the latest (0.10.3).

In any case, this is likely beyond what I am able to help with. Since it runs as usual on other distributions, I must assume it's a packaging or upstream flatpak issue.

You can find the [upstream flatpak issue tracker here](https://github.com/flatpak/flatpak/issues). Even if it isn't an upstream issue you can probably link it to [an NixOS issue](https://github.com/NixOS/nixpkgs/issues) and get some collaboration going.

**Comment by jtojnar** [comment]
I am unable to reproduce this, either when installed globally or as a user.

@wwmm Does this require anything else than flatpak installed globally? Will the GStreamer not be a part of the platform downloaded by flatpak?

@Mounium What desktop environment do you use? On my system I had the `pulseaudio` plugin globally propagated to  `/var/run/current-system/sw/lib/gstreamer-1.0/libgstpulseaudio.so` by `sushi` service. Though, Pulseffects seem to work even if I remove the global plugin installation.

**Comment by wwmm** [comment]
Looking at the flathub build instructions it seems that only gst-plugins-bad is being compiled [https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json](https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json). So it makes sense that the other GStreamer libraries are in a platform. @AsavarTzeth can better explain this

**Comment by Mounium** [comment]
@jtojnar I'm using Gnome, and I do have gstreamer-1.0 available in the current runtime. I've tried different combinations of gstreamer plugins, but running it from a simple terminal prints the same error as in the issue.

I've just tried the same thing with xfce (with hardware.pulseaudio.enable = true) and it does work, although quickly quits with an assertion error.

**Comment by jtojnar** [comment]
@Mounium I just managed to run it on minimal (XTerm only) system

<details><summary>Virtual machine configuration</summary>

```nix
{ pkgs, config, ... }: {
  environment.systemPackages = with pkgs; [
    firefox
  ];

  services.xserver = {
    enable = true;
    layout = "cz";
    xkbVariant = "qwerty";

    desktopManager.xterm.enable = true;
  };

  services.flatpak.enable = true;
  hardware.pulseaudio.enable = true;

  users.extraUsers.j = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = [ "wheel" "networkmanager" ];
    password = "";
    openssh.authorizedKeys.keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYbOlZydfRRCGCT08wdtPcpfSrgxMc6weDx3NcWrnMpVgxnMs3HozzkaS/hbcZUocn7XbCOyaxEd1O8Fuaw4JXpUBcMetpPXkQC+bZHQ3YsZZyzVgCXFPRF88QQj0nR7YVE1AeAifjk3TCODstTxit868V1639/TVIi5y5fC0/VbYG2Lt4AadNH67bRv8YiO3iTsHQoZPKD1nxA7yANHCuw38bGTHRhsxeVD+72ThbsYSZeA9dBrzACpEdnwyXclaoyIOnKdN224tu4+4ytgH/vH/uoUfL8SmzzIDvwZ4Ba2yHhZHs5iwsVjTvLe7jjE6I1u8qY7X8ofnanfNcsmz/ jtojnar@kaiser"];
  };

  virtualisation.memorySize = 1024;
  virtualisation.diskSize = 2048;
}
```
</details>

which confirms Flatpak is pretty stand-alone, so it probably is not a NixOS issue.

![screenshot from 2018-02-04 23-50-53](https://user-images.githubusercontent.com/705123/35783400-a3372ae2-0a06-11e8-8864-babfaba2fb79.png)

**Comment by AsavarTzeth** [comment]
So I will try to summarize and make a few things clear first:

- Flatpak applications and runtimes are true OCI compliant containers. All files delivered are completely independent of your host system.
- When I say "runtime" I am referring to Flatpak runtimes, in this case `org.gnome.Platform 3.26`.
- GStreamer is provided by the `org.gnome.Platform` runtime.
- Flatpak is, perhaps obviously, not responsible for working pulseaudio and dbus instances, which are required.

However, GStreamer in `org.gnome.Platform` is not built to support plugins with external dependencies (LADSPA, LV2, etc...). Because these are provided by `gst-plugins-bad` I need to rebuild that to support this and ship it with the application. The rest are still provided by `org.gnome.Platform`.

If for some reason parts of GStreamer is not found by PulseEffects I can only think of two reasons. Either `org.gnome.Platform//3.26` it is not installed, or it cannot be found for some reason.

You can check what is installed with `flatpak list`.
