### ISSUE TITLE
[Request] Snap package support

### ISSUE THREAD

**Issue by andrebrait** [wwmm/pulseeffects#157]
**Motivation**
Even though Flatpak has nice things going for it, Snaps are compatible with some older distributions (like Ubuntu 16.04 and derived ones) out-of-the-box and provide a more convenient (IMHO, not wanting to start a flame war here, people) way to make apps available for compatible platforms without the need to add repositories by hand. They're very simple to both deploy and install.

Plus, you've got a very nice piece of software here and I'd like to have it available on even more platforms that it already is in a straightforward way.

**What would need to be done?**
To create a Snap and publish it on Snapcraft.io. That should be simpler than building the Flatpak version. I'm already building one for my own usage (I haven't finished it yet, but it seems doable) and I'll submit it to you as a PoC when ready, if you like the idea, of course.

**Who could do it?**
You. Or me. I volunteer to do that, if you think it's a good idea, but you wouldn't do it yourself. Even though this is free software I like respecting the original author's ideas. If you don't like the idea of Snaps or are against it for some reason I'll just forget it and leave it to someone else.

**Comment by wwmm** [comment]
Hi. I see no problems in having a snap package. Feel free to do it and updating the wiki with installation instructions. 

Besides developing PE I am the maintainer of its Arch Linux package. So I doubt I can take that responsibility. Specially because I know nothing about snaps. Just like it happened with the flatpak package someone else will have to do it :-)

**Comment by andrebrait** [comment]
Cool! I'll continue trying then. I've found some problems to generate the snaps on an older system. I'll see how to overcome those and I'll report back as I make progress.

**Comment by JackHack96** [comment]
Oh yeah I'm looking forward to trying it! Also, it could be awesome if the process could be automated, like whenever there's a release the snap is automatically builded (the Flatpak version seems to be manually updated every time, that's why it's still at version 3.1.7)

**Comment by andrebrait** [comment]
Yes, there's a way to automate that using git, but I have yet to generate
the Snap, let alone set this up.

Em 7 de fev de 2018 9:20 AM, "Matteo Iervasi" <notifications@github.com>
escreveu:

**Comment by AsavarTzeth** [comment]
To be fair, the reason the Flatpak version is still at 3.1.7 is because almost every release brings new dependencies and some of them are trickier to add than others. You can automate builds and automatically update the version but you still need to add new dependencies manually. This should apply for snaps as well.

I also ensure license compliance (best as I can), clean up unneeded files (to keep the package small).  On top of this there is a release almost every week and I can't be available every day.

On another note, I do have a plan to semi-automate the Flatpak update process, along with other things.

**Comment by JackHack96** [comment]
Ah that's understandable 👍

**Comment by mikhailnov** [comment]
@AsavarTzeth how do you deal with gstreamer in flatpak, do you build gstreamer for the flatpak? How does the system pulseaudio integrate with it?
In case https://github.com/wwmm/pulseeffects/issues/182 or something else similar is implemented, it seems that building appimages, flatpaks and snaps can become near to impossible, because, as far as I know, those webrtc-related libraries are something like PulseAudio plugins and they have to be built with the system version of PulseAudio to be ABI-compatible with it, but you can't include a prebuilt PulseAudio with plugins into flatpak/snap/Appimage... How will you deal with that..?

**Comment by mikhailnov** [comment]
Well, I've looked closer at webrtc-audio-processing, and the situation is probably not as bad as I have described, because it does not depend from PulseAudio
```
Source: webrtc-audio-processing
Build-Depends: autotools-dev, debhelper (>= 9), dh-autoreconf
```

**Comment by AsavarTzeth** [comment]
All components of a flatpak are built from source. It is the only way to ensure ABI comaptibility.

PulseAudio is available via a socket connection, as usual. You just need to allow that socket inside the sandbox. Permissions are documented at [docs.flatpak.org](http://docs.flatpak.org/en/latest/sandbox-permissions.html). I believe with snaps the pulseaudio plug is equivalent to `--socket=pulseaudio`.

You may borrow whatever you need for building from my [manifest](https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json).

Or just use Arch Linux's PKGBUILD files for inspiration. They are about as simple as it gets.
