### ISSUE TITLE
[FAQ] Where to find predefined equalizer presets?

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#161]
Version 3.1.7.

Where to find predefined equalizer presets?

**Comment by JackHack96** [comment]
If you want, I created a repository with 4 presets, you can find it here [https://github.com/JackHack96/PulseEffects-Presets](https://github.com/JackHack96/PulseEffects-Presets).
Otherwise if you want other presets, there is `swag4swag` repository [https://github.com/swag4swag/PulseEffects-Presets](https://github.com/swag4swag/PulseEffects-Presets)

**Comment by JackHack96** [comment]
@wwmm Should we add a question in the FAQ?

**Comment by wwmm** [comment]
It is a good idea :-) But maybe it is better to create a section with a name like `Community Presets` than to put in the FAQ. This way we can have other third party presets there without making the FAQ section too cluttered.

Considering that not everybody has the habit to click in the wiki a link to this section in the readme would be appropriate. It could be between the links to the command line and bug report sections

**Comment by JackHack96** [comment]
Done ;)

**Comment by WarpspeedSCP** [comment]
One question, I've looked around, but I have no idea where to drop presets I have downloaded from the web, where do pulseeffects presets reside on disk?
