### ISSUE TITLE
Use default system window decorations instead of custom

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#169]
Currently it looks like that PulseEffects enabled its own windows decorations instead of using default system's.

Can the buttons, "Presets" and menu button simply moved into window from the title bar?

**Comment by wwmm** [comment]
They can not be moved from there. The menu where you can access the `about window` is automatically moved to the window when not in gnome because it is the traditional kind of menu. 

Although I understand that some people prefer server side decorations PulseEffects is developed with client side decorations in mind. No plans to change that.

**Comment by AndydeCleyre** [comment]
FWIW, the old [gtk3-nocsd](https://github.com/ZaWertun/gtk3-nocsd) hack, when used in its prefix form (launching this app with `gtk3-nocsd pulseeffects`) still works (for now) to correct the assault on consistency, functionality, and user choice that is the mandatory CSD.
