### ISSUE TITLE
No sound and error loop.

### ISSUE THREAD

**Issue by kevinsmia1939** [wwmm/pulseeffects#17]
I use Xubuntu 16.04. I install the newest pulseeffects, but it told me to install gtk+ 3.20 but I have gtk+ 3.18. I then install new repo from sudo add-apt-repository ppa:gnome3-team/gnome3-staging and sudo add-apt-repository ppa:gnome3-team/gnome3 and update. I tried restart once but upon starting pulseefects with GSETTINGS_SCHEMA_DIR=share/glib-2.0/schemas/ ./pulseeffects
I got this infinite loop of error... however pulseeffect did start but no sound.
http://i.imgur.com/6VRE8Fs.png

**Comment by wwmm** [comment]
Hi, the error 'unknown type GstValueList' is happening because the latest versions of PulseEffects need Gstreamer 1.12 or above. If you do not have it available for your distro use PulseEffects 1.4.1 [https://github.com/wwmm/pulseeffects/archive/v1.4.1.tar.gz](https://github.com/wwmm/pulseeffects/archive/v1.4.1.tar.gz)

**Comment by kevinsmia1939** [comment]
Ok, thanks man, I use ppa-purge to remove gtk 3.2 downgrade to 3.18 and install pulseeffects 1.4.1 works fine now.
