### ISSUE TITLE
Remove "python3" prefix when running background app

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#170]
When looking into "ps aux" command output I see this: "python3 /usr/bin/pulseeffects --gapplication-service"
This means it's not possible to simply run "pkill pulseeffects" or "killall pulseeffects" for simplicity.
Please remove the "python3" prefix, it's redundant.

Version 3.2.0 installed from http://ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu

**Comment by wwmm** [comment]
This is something that can not be done. If you take a look at PE desktop launcher file you will see that there is no `python3` there. Just a `Exec=pulseeffects`. Bash is the one putting `python3` there because that is the way python applications have to be executed. There is no way around that.

If you want to kill PE from command line you will have to run `pulseeffects -q` as explained here [Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options)

**Comment by teneri66** [comment]
Thank you.
