### ISSUE TITLE
Warning may occur

### ISSUE THREAD

**Issue by teneri66** [wwmm/pulseeffects#172]
16:41:27.72 - PulseEffects - WARNING - (gerror=GLib.Error('Can't record audio fast enough', 'gst-core-error-quark', 13), debug="gstaudiobasesrc.c(847): gst_audio_base_src_create (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nDropped 39249 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.")

**Comment by wwmm** [comment]
This warning is from the microphone pipeline and is harmless. It does not affect processing of audio apps output (vlc, chrome, mpv, etc) and it only happens once when the microphone signal is starting to be processed. I am not sure if the problem is at GStreamer or Pulseaudio but I did everything I could do on my side to reduce these messages to a minimum
