### ISSUE TITLE
Can't use PulseEffects with Telegram

### ISSUE THREAD

**Issue by Bleuzen** [wwmm/pulseeffects#188]
Hi,
I try to get Telegram Voice Messages recordings working with PulseEffects, but there is a problem when using PulseEffects with Telegram. Telegram always uses the default devices set in PulseAudio.
So for example when I try to record a voice message and have PulseEffects running and try to enable the mic effects for Telegram, it directly changes back, because Telegram always uses the default device, we can't change this. If I change it, Telegram changes it back. If I enable "enable all apps" in PulseEffects, Telegram changes it back and records from the default one. No way to change the (recording) device without making a new one the default.
There is already a bug report at Telegram for this, but nobody cares for over a year now.

So the only way / a little workaround to use Telegram with PulseEffects is, to set the PulseEffects sinks as default before starting Telegram.

But at least for the mic: I can't. Because of this:
This are my input devices:
![grafik](https://user-images.githubusercontent.com/12885163/37783638-481887a0-2df6-11e8-853d-a4d5b12d9e1c.png)
And this are my output devices:
![grafik](https://user-images.githubusercontent.com/12885163/37783656-5380c710-2df6-11e8-84f7-5c25654df81a.png)

As you can see, the PulseEffects streams are both displayed as Output devices. So I can't set the "PulseEffects(mic)" as default Input device, because it is no input device.

So maybe .. would it be possible to make the "PulseEffects(mic)" a input device?
Or do you know a better way to make PulseEffects compatible with Apps like Telegram, that always use the default device?
At least to make a 'virtual' device and set it as the default recording device is the only idea I have right now.

**Comment by wwmm** [comment]
PulseEffects(mic) can not be a input device because it is a Pulseaudio null sink. Inside PE there is a GStreamer pipeline that is recording the default input device (usually the mic). After applying effects to the signal this pipeline plays it in PulseEffects(mic). As all Pulseaudio's null sinks PulseEffects(mic) has an associated monitor device called `PulseEffects_mic.monitor`. When the app switch is turned on in PE window the app is moved from the default input to `PulseEffects_mic.monitor`.  You can see this device in Pavucontrol if you choose `Show: All input devices` in the input devices window.

Although it is probably possible to make `PulseEffects_mic.monitor` the default input device I don't think this is a good idea. PE automatically switches to the current default device. If you make `PulseEffects_mic.monitor` default PE will record it instead of the microphone and enter in a loop recording silence or a noise from itself.

In other to support telegram I will have to add a way for the user to disable the automatic source switch done by PE. It will also be necessary to somehow expose in the interface a way to select the device PE should record and apply effects. With these changes `PulseEffects_mic.monitor` could be selected as default input. I think it makes sense to add these switches. I just have to think about the best way to add them in the interface

**Comment by wwmm** [comment]
The code in latest master allows the user to select the input and output device for the current session. Could you test if with this you can make telegram work? 

The device selection has a few rough edges but it should work in cases like yours. The selections are not remembered when PE is closed and it is not clear yet what can happen when the custom device selected by the user suddenly disappears. I will polish this in the next versions.

**Comment by Bleuzen** [comment]
Yes, this works with Telegram. Great, thank you! :D
