### ISSUE TITLE
Stretched window

### ISSUE THREAD

**Issue by prescott66** [wwmm/pulseeffects#19]
After installing latest version (1.5.1) the main window is extremely stretched and cant be changed nor resized. Maybe is problem with new slovak strings, that are longer that english strings.

Screenshot:
![scrnshot_pulseeffects](https://cloud.githubusercontent.com/assets/735265/26771459/b5a4fc30-49be-11e7-9357-5e52a66bac9e.png)

**Comment by marc2377** [comment]
@prescott66 In my system, the minimum dimensions appear to be about 1496x844. I can make it larger, but not smaller. Do you confirm this?

**Comment by wwmm** [comment]
Hi prescott66, it is definitly because of the larger strings. Being more specific the equalizer pre amplifier string. I will investigate if I can do something to reduce the space between the equalizer controls. Right now I am forcing the same horizontal size for all of them because I could not find another way to have the equalizer controls to horizontally resize together with the main window...

marc2377, I could not find a way to resize to smaller sizes. The widgets size put a lower bound on window size.

**Comment by wwmm** [comment]
Hi,

I pushed to the master branch some changes to the interface that seem to have solved this issue. Could you test it?

**Comment by prescott66** [comment]
Thank you for your activity. i will test changes in next release (using AUR repo in arch)

**Comment by prescott66** [comment]
Fixed in v1.5.2
