### ISSUE TITLE
[Request] X/GTK as an optional dependency

### ISSUE THREAD

**Issue by cshapeshifter** [wwmm/pulseeffects#198]
It would sure be nice being able to use PE on a server (e.g. this raspberry pi I want to use to play music) without having to install GTK and X. In place of full CLI control, I'd just create a preset on another machine and then load it on the server.

I had a quick look if I could fix up an alternative "main" application and honestly got discouraged seeing that all the UI code is interleaved with the pulse functionality code (i.e. every singe effect would need to be edited, removing `init_ui` and a lot of other things. From the software architectural stand-point, it would have been nice if the functionality were provided separately from the UI, but it sure is too late for that now. Well, I'll put this up anyway as a thought, should there ever be a rewrite or major refactoring up ahead.

For anyone interested, probably the best workaround for now is to use Xvfb:
```
Xvfb :1 &
export DISPLAY=:1
pulseeffects --gapplication-service &
pulseeffects -l BassReduce # preset copied to .config/PulseEffects/BassReduce.preset
```
This can be turned into a systemd service by creating something like `/usr/local/bin/pulseeffects-xvfb`: 
```
#!/bin/bash

if [[ "$1" = "start" ]]; then
	pkill Xvfb
	sleep 1
	Xvfb :43 &
	sleep 3
	export DISPLAY=:43
	pulseeffects --gapplication-service
fi
if [[ "$1" = "stop" ]]; then
	pulseeffects --quit
	pkill Xvfb
fi
```
and creating a user service like `.config/systemd/user/pulseeffects-xvfb.service`:
```
[Unit]
Description=Pulseeffects inside Xvfb

[Service]
Type=simple
ExecStart=/usr/local/bin/pulseeffects-xvfb start
ExecStop=/usr/local/bin/pulseeffects-xvfb stop
Restart=on-failure

[Install]
WantedBy=default.target
```
and starting/enabling it like so:
```
systemctl --user daemon-reload
systemctl --user start pulseeffects-xvfb
systemctl --user enable pulseeffects-xvfb
```

**Comment by wwmm** [comment]
Hi! I understand your point and although it is not something I would do I can see that many would. Actually a long time ago someone asked for this feature too. But it never happened because of the higher development burden this `app <-> server` model would put on me. 

With the exception of localization support I am the one implementing everything in PE. Separating the server from the application interface and making them talking to each other through some protocol would give me much more work. And it was not clear if I would be able to use Gsettings bindings from the ui elements to GStreamer parameters with the plugins in a separate process. And as I never needed a server only mode I never considered going in this direction.

Now that PE code is reaching 10000 lines there is also the refactoring barrier. At least for now I do not have any intention of doing such a big rewrite. So I will close this issue. But I think that it would be good to have the steps you gave in your post in a place more visible to other users. Could you add a section to the [wiki](https://github.com/wwmm/pulseeffects/wiki) with them?
