### ISSUE TITLE
Previously chosen options are not selected when opening the configuration sub-group

### ISSUE THREAD

**Issue by marc2377** [wwmm/pulseeffects#20]
All sub-groups have a Configuration button with a gear button, which displays the respective options.

However, for most of these subgroups (namely: Input Limiter, Reverberation, Compressor and Equalizer), reopening them after having previously selected an option won't highlight which option is active. This doesn't happen for the Test Signal subgroup.

To be clear, the chosen settings are saved and applied, the issue here is mostly a cosmetic one.

**Comment by wwmm** [comment]
Hi,

Thanks for opening this issue. Right now I am clearing the selected option once the menu is closed. I did that because if the user changes any of the controls after selecting a preset the effect being applied is not the one from the preset anymore. I thought this would be confusing for some people. But as I am not a interface designer nor a professional programmer (I am a physicist XD) there may be a better way to handle this that I am not aware of.

One thing that could be done is clearing the selection as soon as the user changes any of the related controls. But given the amount of controls already exposed on the window it seemed to me I would have to add a lot of code for doing a small thing. Maybe radio buttons are not the best for this tasks and something else should be used from a interface design point of view... I just have no idea...
