### ISSUE TITLE
How to force PulseEffects to start with a specified preset

### ISSUE THREAD

**Issue by dln949** [wwmm/pulseeffects#201]
Running Ubuntu 17.10, Gnome Shell 3.26.2, x11.  

Installed PulseEffects 3.2.1 via Flatpak.  

I have created a preset, given it a name, and saved it.  

How do I make PulseEffects start using that preset?  Everytime I start PulseEffects, it starts in its "generic" settings state.  

Thanks.

**Comment by skeevy420** [comment]
`pulseeffects -p` will show available presets

`pulseeffects -l "name_of_preset"` will start pulseeffects with the selected preset

**Comment by skeevy420** [comment]
I'm not 100% if this will work since I'm using a modified default preset that gets loaded by default and I have some stuff to do and can't test this for a few hours, but if you `edit line 4 of ~./config/autostart/pulseeffects-service.desktop` you should be able to have pulseeffects load a predefined preset on login.

change it from
`Exec=pulseeffects --gapplication-service`

to
`Exec=pulseeffects --gapplication-service -l your_preset_from_dash_p`

**Comment by wwmm** [comment]
@dln949 exactly what is generic? Every PE settings is saved in a dconf key that is reloaded when PE starts. You should see the last used settings and not something generic

**Comment by dln949** [comment]
@wwmm  Well.... Sadly I was not seeing the last used settings.  Instead, I saw the  - what do I call it? - "default" settings when PulseEffects is first installed.  However.....  

I uninstalled the flatpak package, and installed the debian package, and this problem no longer exists.
