### ISSUE TITLE
Is there a way pulseeffects install on ubuntu 16.04?

### ISSUE THREAD

**Issue by ableabhinav** [wwmm/pulseeffects#206]
I really want to have an equalizer on my system. I wanted to try this but it seems it depends on the newer version of gstreamer. Is there a way to install it on 16.04, like building from the source?
Any help appreciated

Ubuntu 16.04.1
Kernel 4.13.0-38-generic

**Comment by wwmm** [comment]
Unless you intend to compile the newest GStreamer too I think your only option is to use flatpak [Package-Repositories](https://github.com/wwmm/pulseeffects/wiki/Package-Repositories)

**Comment by ableabhinav** [comment]
Thanks for the help, will try using flatpak repositories. Will there be any difference in usage when installing from flatpak as opposed to using the distribution packages?
Thanks again

**Comment by wwmm** [comment]
As far as I remember the only thing not working when using flatpak is the menu option `Start Service at login`. This feature needs to create an autostart file at `~.config/autostart` but flatpak sandboxing denies that. You will have to create an autostart file by yourself using flatpak commands to start PE

**Comment by ableabhinav** [comment]
Ok, if auto-starting works using flatpak commands, then I don't see any issues with it. Thanks!

**Comment by wwmm** [comment]
IT should work. What the menu option does is create a file named `pulseeffects-service.desktop` with:

```
[Desktop Entry]
Name=PulseEffects
Comment=PulseEffects Service
Exec=pulseeffects --gapplication-service
Icon=pulseeffects
StartupNotify=false
Terminal=false
Type=Application
```
in the directory `~.config/autostart`. You just have to modify the Exec entry with the flatpak commands

**Comment by wwmm** [comment]
KDE users also have to unload `module-device-manager`. Take a look at point `3` in [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ). Both modules should be fixed when Pulseaudio 12 is released

**Comment by ableabhinav** [comment]
I have unloaded the module. checked using `pactl list modules short
` Still no sound. When I select Built-in Audio Analog Stereo audio works, but selecting pulseeffects(apps) as default results in no sound, though there is some activity in PE. Another thing, inside the app, the blue colored bar below current application shows my mic activity. Is it what its intended to do?

**Comment by wwmm** [comment]
The level meter for mpv should show its audio output. Only when applying effects for mic (mic icon at the top left) this shows microphone activity.

Do not choose `PulseEffects(apps)` as default output. This may break PE routing. PE redirects apps output to `PulseEffects(apps)`  and then records from it to apply effects. After this it plays the result to the default output device. That is why it may break if you have its sink set as default.

If you car hear sound from mic something messed with the PE routing I described above. As far as as know there are only 2 things that do that: `module-device-manager` and `module-switch-on-connect`. I am not sure about what else could be doing that in your case.

Put here images from pavucontrol tabs while mpv is playing and PE is opened. Maybe they will show some clues

**Comment by wwmm** [comment]
1) When changing the volume through the app volume slider in PE there can be stuttering indeed. I noticed that they are latency dependent. If I choose a latency of 1 ms instead of 10 ms in PE settings menu They disappear. The downside is that Pulseaudio uses much more cpu when we decrease latency. I still don't know how to fix this. Be careful when playing with the latency values because depending on sampling rate and maybe hardware you may crash PE. If this happens use dconf editor to reset the latency values

2) Depending on the buffer value you may notice some delay in a few situations. I usually have it at 40000 micro seconds and the latency at 10000 micro seconds. Decreasing the latency lower buffer values can be used.

3) You can run it in background. Just execute it in service mode [Command-Line-Options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options). This way you can open and close the window as desired without loosing the effects. When installing through regular distribution packages like debian or rpm the option `Start Service at Login` in PE menu will do that for you in the next login. Unfortunately this does not work with flatpak because of its sandboxing. In this case you will have to create your own autostart file at `~.config/autostart`. Take the autostart file a few posts above as model

4) Depending on your processor PE plugins can be a little heavy. I usually use it with my ryzen 1700 and the load is negligible. But in my laptop I notice that if I enable too many plugins it uses more cpu than I would like. A few plugins are heavier than others. The Bass enhancer and the exciter are among the ones that use more cpu. Unfortunately as I did not implement any of these plugins there is nothing I can do about their performance. I am just exposing them in the interface.

**Comment by mervick** [comment]
The easiest way to install on ubuntu 16.04
```sh
sudo add-apt-repository ppa:yunnxx/gnome3
sudo apt-get update
sudo apt install pulseeffects
```
