### ISSUE TITLE
Have a small "info" button near the "buffer-time" option to aid users in setting Latency

### ISSUE THREAD

**Issue by marc2377** [wwmm/pulseeffects#21]
The default buffer window for this program is 60ms, which I believe is a bit too high of latency for most multimedia/gaming scenarios.

In my system I can lower this down to 24ms in normal circumstances, but in reality, the value of 30ms is the minimum I can set it to without introducing audio stuttering/clipping during high CPU usage. So I have just settled with 33ms, which appears to be a well-accepted default (you can see the discussion here, for instance: https://lists.freedesktop.org/archives/pulseaudio-discuss/2014-March/020174.html).

This 33ms setting is working very smoothly, even with sustained 100% CPU load, plus heavy I/O activity. This is for 48 KHz sources.

I'm a previous MS Windows user, and in Windows I used [ViPER4Windows](http://vipersaudio.com/blog/?page_id=59). The default latency for this software is 46ms, which is already quite noticeable.

So in this issue I'm really making two suggestions:

1) Consider lowering the default latency for PulseEffects
2) Introduce a small "info"  icon (for help, possibly simply a round "i" or "?" symbol) right near the Buffer-time option so that new users can just click it and read about latency and how to better adjust it.

I though about having pre-set latencies but that idea doesn't really appeal to me.

Now to be a bit off-topic, you are doing a **great** work in this project. Congratulations, and best regards.

**Comment by wwmm** [comment]
Hi,

It is strange it is defaulting to 60 ms because a value of 100 ms is set as default in the dconf configuration. Anyway I agree that the value could be smaller. I usually have it at 50 ms and I can also go down to around 30 ms. I just do not know if these values are somehow hardware dependent. If they are a default value that is to small could bring a bad first experience for many users.

Something that would be fast and easy to add is to show a tooltip when the user puts its mouse pointer over the buffer control. Unless the idea is to have a long text talking about latency this would be enough. Do you any text in mind to put there?

The buffer-time setting controls the option `buffer-time` of the gstreamer plugins pulsesrc and pulsesink (I am setting the same value for both). I am not sure if they are the only ones contributing to the overall latency as these plugins also have another option called `latency-time` that defaults to 10 miliseconds.
