### ISSUE TITLE
Please add built-in presets

### ISSUE THREAD

**Issue by Paramood** [wwmm/pulseeffects#242]

**Comment by wwmm** [comment]
I assume you want presets for the equalizer. I am totally in favor but I have no idea about how those generic presets for music genres are done. So someone else will have to do that.

Once someone makes these presets it would also be necessary to think how to expose them to the user. Considering that now the equalizer can have different number of bands for each presets it does not sound feasible to have a button for each preset in the interface. I think we will have to install these presets files somewhere in `/ush/share` and point the user to this path when here clicks in the `import presets button`.

I will leave this issue open in case someone with time and knowledge is interested in providing these presets

**Comment by flipwise** [comment]
If anything is going to be built-in, I also think it makes sense to only include equalizer presets. There's community presets for everything else. 

It would be easiest to just strip the presets from a known project. The problem is that whenever I've seen existing presets, they were in proprietary software. But I think this Audacious file list most if not all commonly used presets in many programs: https://gist.github.com/kra3/9781800. Could be that too few bands are included and so this cannot be used, however.  Besides those, a must have preset would definitely be the Perfect EQ, as incorporated here e.g. - https://github.com/JackHack96/PulseEffects-Presets.

As for how to implement it, maybe a simple drop-menu in the equalizer settings would work? But maybe this would look bad if there are too many presets.

**Comment by wwmm** [comment]
I think that this list can be big if we offer presets for different numbers of equalizer bands. The ones from Audacious link have 10 but the default in PE is 30 and some people prefer 12 or 15.

But worse than this list size is having the equalizer presets files using a different format than standard  PE presets that have all plugins in it. I definitely do not want to increase even more the complexity of PE code base.

**Comment by flipwise** [comment]
Yes, both of these things are an issue. It may be the best to simply have 30 band presets, as is the PE default. But what happens when a 30 band preset is imported and reduced to a say a 10 band one? Would this result in undesired median values applied to new frequencies, ie. would it be different than just directly importing an equivalent 10 band one? 

Also, I looked into those Audacious presets and they're actually just ripped from the default Winamp presets. The Winamp equalizer did unfortunately have just 9 bands. But as for the presets' format, of course I didn't mean to say that we should import presets directly, but that it would be useful to already find defined preset names and values. Then they could just be translated into the .json format.

**Comment by wwmm** [comment]
If you import a 30 band preset and then changes the equalizer to have 10 bands you will loose the last 20 bands of the preset. No changes to the frequency and width of the first 10 bands. In other words it does not automatically become a 10 bands graphic equalizer preset. Usually not want people will want. It is the same as opening the preset file and deleting the last 20 bands and updating the `num-bands` parameter accordingly. 

There is no problem in using Winamp presets. Just to clarify let's consider a 2 bands equalizer preset:
```
"equalizer": {
            "state": "true",
            "num-bands": "2",
            "band0": {
                "gain": "0",
                "frequency": "22.589254117941671",
                "width": "5.1785082358833456",
                "type": "peak"
            },
            "band1": {
                "gain": "0",
                "frequency": "28.438186042552807",
                "width": "6.5193556133389272",
                "type": "peak"
            }
}
```
As long as the number of bands and the parameters for each band are specified in the preset we can use any preset we want. PE will change its interface to match to what is in the preset

**Comment by wwmm** [comment]
If we just install these presets in a place like `/usr/share/PulseEffects` and then use it as default preset import location we can support presets made for different equalizers easily with no need to complicate the interface. Would this be a problem to the flatpak package @AsavarTzeth ?

**Comment by AsavarTzeth** [comment]
As long as `/usr` is defined by the meson prefix, then no I don't see any problems with this.

**Comment by AsavarTzeth** [comment]
There may be some problems with this after all.

- /app is read-only and hidden to the user outside of PulseEffects. If a user wanted to copy it as a base for their own that would be a difficult process.

I may have an extension of you plan.

At build time install presets in `prefix/share/PulseEffects`. But when a user runs the app also copy those presets to the user presets directory. Keep the current default import location.

That way all presets are easy to find in one place, and more importantly reachable outside the PulseEffects container, ex. from a file manager.

**Comment by wwmm** [comment]
It can be done. But I'd like that only user made presets were visible in the preset menu and that only bundled presets were visible in the import dialog. At least to me it does not make much sense to see presets I have already made as an option to be imported. At this moment any `*.json` file present in the presets folder is shown in the preset menu. Adding a prefix helps to blacklist bundled presets in the menu. But when the user opens the dialog he will see both bundled and custom presets. It may be confusing. Maybe we could create a folder exclusive to bundled presets inside the presets folder

I am ok with a `contrib/presets` folder in the repo.

**Comment by AsavarTzeth** [comment]
Oh right, sorry but I completly forgot all presets in the user config were added to the menu. I knew it, just forgot it in my haste.

In that case, yes perhaps a sub directory would be a good solution. If the subdir has an obvious enough name a first reaction would probably be to find out what's inside.

**Comment by wwmm** [comment]
No problems. I am thinking about creating a subdir in the user config folder and making the import dialog pointing directly to it. This way it will not show the user custom presets. Nothing will change when populating the menu because the search is not recursive

**Comment by wwmm** [comment]
In any case I will wait for someone to appear here with these community presets before starting any change in this direction.

**Comment by flipwise** [comment]
I've been trying to port the Winamp presets to .json but I want to copy just the equalizer information. The generated .json file contains a lot information and settings I do not want to affect. If I remove everything except the equalizer settings, this file crashes PE. Is it possible to just have the equalizer settings in the .json file?

**Comment by wwmm** [comment]
What is the crash error?

In any case this is a disadvantage of adding these presets this way. PE presets were always meant to save all the parameters as not everybody uses only the equalizer. But it should load the default value of any parameter that is missing in the preset file. It was not supposed to crash in this situation.

**Comment by wwmm** [comment]
Although I still would like that PE did not crash in this situation I think it is better to change a little the approach and show these presets in a list accessed in the equalizer interface. Paste here the json files with only the equalizer presets and I will think about how to integrate them

**Comment by flipwise** [comment]
OK, if I format it differently it doesn't crash but it won't load the equalizer preset.

Debug info just says: (pulseeffects:6698): pulseeffects-DEBUG: 15:51:15.527: presets_manager: loaded preset: /home/filip/.config/PulseEffects/Winamp_Party.json

Here is the file: 
[Winamp_Party.zip](https://github.com/wwmm/pulseeffects/files/2124151/Winamp_Party.zip)

Also, could I ask you what you think the best way of porting the Preamp feature is? So in all those Winamp/Audacious configs Preamp is set at 0.375 and then all unchanged bands are at 0.375 as well. Since PE doesn't have Preamp, should I just add 0.375 to every value I'm porting?

**Comment by wwmm** [comment]
PE 3.x had `input-gain`(preamp) and `output-gain` controls. I could bring them back. It is not a problem. But in PE the units are in decibel so this 0.375 value will become `-8.52` (20*log10(0.375)). And the parameter would be called `input-gain`. So you would have to do this in the presets for example:

```
"equalizer": {
            "state": "true",
            "num-bands": "10",
            "input-gain":"-8.52",
            "output-gain":"0.0",
            "band0": {
                "gain": "4.875",
                "frequency": "70",
                "width": "46.670000000000002",
                "type": "peak"
            }
}
```

**Comment by wwmm** [comment]
Wait. Is this 0.375 value already in decibel?

**Comment by wwmm** [comment]
If it is use it and not `-8.52`

**Comment by wwmm** [comment]
Considering you have a few bands with `0.75` as gain I'd say `0.375` is also in decibel. I am so used to think values smaller than one as being in a linear scale that I assumed it as not in decibel. So just use `"input-gain":"0.375"` in the presets files

**Comment by flipwise** [comment]
I think so, it should be decibels. I googled a bit and it seems like Winamp did use decibels for EQ changes. Okay, with input gain I can just use the same values as in the sample file. 

And also, do you think that the width is properly set? When I generated the frequencies for 10 bands in PE, they didn't match Winamps so I fixed this. But then I also had to change the width. I saw that when PE calculates frequencies for 10 bands,  Q was always 1.50. So for the Winamp frequencies I applied a width that also results in Q=1.50.

**Comment by wwmm** [comment]
As far as I remember there are more than one standard for equalizer center frequencies. I don't know exactly which one GStreamer uses. I just looked at its source code and took the equation they use. Winamp presets are probably using other standard. It is not a problem. If you have Winamp presets center frequencies and widths my suggestion is that you just use them. If you change the Q factor or any other parameter the preset will not have the exact effect its author had in mind

**Comment by flipwise** [comment]
That's exactly my concern. I ran Winamp in Wine and took the frequencies from there, I just don't have any information about the widths. I will look into this more first.

**Comment by wwmm** [comment]
If you cannot find the width try to find the Q (quality factor). We can reverse engineer the width with it `width = center_frequency / Q`

**Comment by wwmm** [comment]
It would also be good to know if there is any problem with copyrights

**Comment by flipwise** [comment]
Hmm good point. I will look into this first so that these two issues don't become a headache.

**Comment by wwmm** [comment]
If Audacity is using Winamp presets it should not be a problem to do the same. But it is good to check just in case

**Comment by flipwise** [comment]
Ha, the thing is that even though Audacious copies much from Winamp (if you use the Winamp skin), it actually does not come with any predefined presets. Maybe they did not know how to extract them, but maybe your doubt about copyright is justified. I don't know how that guy obtained the presets, but they definitely need to manually added to Audacious.

**Comment by flipwise** [comment]
I figured out how he likely did it. It's actually fairly trivial even for a non-tech savy user to obtain .preset files of Winamp's default presets. One can simply load each of them in Winamp, save them as .eqf, import as .eqf in Audacious and then save as .preset in Audacious. This may mean they could have been included in Audacious. Since Winamp seems to be abandonware, maybe we can just directly contact the lead dev of Audacious (https://github.com/jlindgren90), he might know something?

**Comment by wwmm** [comment]
It is worth trying. He probably had a reason to not including these presets if Audacious can easily import them

**Comment by wwmm** [comment]
I remembered that GStreamer has presets for their 10 bands equalizer [https://github.com/GStreamer/gst-plugins-good/blob/master/gst/equalizer/GstIirEqualizer10Bands.prs](https://github.com/GStreamer/gst-plugins-good/blob/master/gst/equalizer/GstIirEqualizer10Bands.prs). I added them to PE
![screenshot from 2018-06-22 14-27-18](https://user-images.githubusercontent.com/16225172/41790652-9df7b710-7629-11e8-81a9-6fb6d8fb68b0.png)

@AsavarTzeth I realized that there was a better approach that should work for everyone. Embedding the presets files in the executable binary using gresource. I already do that with the glade files and a few custom icons used in PE interface. So I see no reason for flatpak to have problems with these presets.

I updated the master branch with these changes. Presets files can be seen in the presets folder [https://github.com/wwmm/pulseeffects/tree/master/data/presets](https://github.com/wwmm/pulseeffects/tree/master/data/presets). As I reorganized a littl the data folder there are small differences when running directly from the sources [https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository](https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository).

Vlc has presets but they look the same as the ones from GStreamer.

**Comment by flipwise** [comment]
Awesome! What do you think about maybe integrating Perfect EQ as well, e.g. as here: https://github.com/JackHack96/PulseEffects-Presets/blob/master/Bass%20Enhancing%20%2B%20Perfect%20EQ.json . It's also 10 band and IMO one of the best presets you can find. 

And also if @JackHack96 would be okay with it, of course.

**Comment by wwmm** [comment]
As long as he is okay with it I see no problems

**Comment by JackHack96** [comment]
Excuse me I didn't receive any notification (I must check GitHub settings).

Anyway there's no problem with integrating ;)

I only have a question though: is there something like preamp in the equalizer?
Because it sometimes causes clipping, and I should lower the master channel for preventing it.

**Comment by wwmm** [comment]
Hi! In the latest PE release the equalizer has input (preamp) and output gain controls.

Do you have any suggestion about how to name your preset? Considering that we can have presets from anywhere with any number of bands I decided to name GStreamer's presets like `gstreamer_pop` instead of just `pop` for example. In other words the idea would be to have the source of the presets followed by an underline and then the preset name.

**Comment by JackHack96** [comment]
Ok, I'll wait for the flatpak update then ;)

As for the name, uhm, I'm not very good at naming (like all programmers xD).
I made the presets based on the link you can find in my repo, so we could call it something like `zihad_perfecteq` or simply `perfect_eq` :)

**Comment by p-chan5** [comment]
Hi everyone! I'm a bit late to this thread (4 years xD). A few months ago I was also looking for some presets for `PulseEffects` however I ran into the same problem. **There was no one who could offer that variety or quality for this powerful tool.** So I got to work and created the [EasyPulse](https://github.com/p-chan5/EasyPulse) project where **I manage a set of presets (15 exactly)** for `EasyEffects` and `PulseEffects` with regular updates. There was no need to port the configuration of any tool because they are original! And with the same license as [easyeffects](https://github.com/wwmm/easyeffects) the [GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.en.html) I tried the `GStreamer` presets and @JackHack96 's but I felt they were missing some magic! ✨️ Could you give them a look? It would make me happy if I could participate in the development in this way.

**Comment by wwmm** [comment]
>Could you give them a look? It would make me happy if I could participate in the development in this way.

I think it is complicated to do more than what is being discussed at #1771. When I began this project I used to embed some equalizer presets. But as soon as I decided to move to a better equalizer the old presets were useless. Since then I have avoided embedding presets. Specially because the results will depend a lot on the user hardware.

**Comment by p-chan5** [comment]
Thanks for your reply! I also think it depends of each user. I made [my presets](https://github.com/p-chan5/EasyPulse) using your tool (plus a GUI of LSP and Calf Studio Gear) In my free time I like to learn Music Production and Mixing so it wasn't complicated. Just some patience and discipline to achieve good results. For now I will continue to improve them! I hope one day you can give them a try. 😉️
