### ISSUE TITLE
Why the sudden switch to JSON for presets?

### ISSUE THREAD

**Issue by tehlordvortex** [wwmm/pulseeffects#244]
Hello! As the title implies, I'm wondering why there was a switch to JSON for presets? The wiki hasn't even been updated to reflect that. I only realized when my presets weren't showing up, so I created a new one, checked `~/.config/PulseEffects` and it was saved as JSON.
Is there a way to convert from the old format to the new one?

**Comment by wwmm** [comment]
Although I also edit the wiki when it is necessary and I have time that place is intended to be community maintained. I am not responsible for the community presets section for example. So whenever there is such a big release like version 4 with many changes compared to the previous version it will take some time until the wiki reflects all the changes.

When I took the decision to do a complete rewrite of PE in version 4 moving from Python to C++ I took the opportunity to do in a better way everything that was done by improvising or in a not elegant way in older versions. I also decided that I would drop any workaround for libraries bugs that were already fixed by their respective developers in their latest releases. There was no point in rewrite the whole thing from scratch while living workarounds for fixed bugs there. The presets format is one more of these changes. When I started PE I didn't have such a high goal. I didn't imagine that we would have so many plugins and apply effects to both applications output and input while being able to save all this in a preset. The more I wanted to use subsections and arrays the clearer it was that I should move away from INI as presets format. And there would be no better moment than a total rewrite to do this.

Unfortunately the time I have to work on PE is spent on more important areas of its code. No time to write conversion utilities from the old format to the new one. Sorry
