### ISSUE TITLE
Must use Pulse Audio Control

### ISSUE THREAD

**Issue by WarDogSniper** [wwmm/pulseeffects#251]
OS: Ubuntu 18.04 LTS x86_64 
Host: MS-7641 4.0 
Kernel: 4.15.0-23-generic 
DE: MATE 
Pulse Effects v4.08

I'm using the PPA to install
I tried to follow a few of the other Pulse Audio Threads but got lost on a few tails.
anyway the problem was / is I have ( 0 ) Zero control with my Master Volume and must adjust it
with pavucontrol ( Pulse Audio Control ) PAC

Before the update to v4.10 I could trick it out on a reboot and imitatively running PE first then opening  up an audio/video file and all would be good.   (Sometimes) not always but more often then not.

I built v4.08 and re-installed it hopping everything would go back but ( No Luck )
but now I have no other option but to use PAC for better control

from what I could gather from the threads I might not be the only one with this issue..?

Still the Best Audio PERIOD!

**Comment by wwmm** [comment]
I did not understand your description of the problem. Exactly for what do you need pavucontrol? Is this somehow related to the points `4 and 5` at [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ)?

**Comment by WarDogSniper** [comment]
Sorry here are some photos that will explain what I am going through and I didn't notice it until now that the Master Volume was controlling the PE Mic

I hope this explains it for ya

Controlling PE Mic at FULL
https://kek.gg/i/7fkpQD.png

Controlling PE Mic at ( 0 ) Zero
https://kek.gg/i/3dv3Tc.png

What master volume should be controling...
https://kek.gg/i/3GF39h.png

So the last picture shows the only way I can control my main volume level.

**Comment by wwmm** [comment]
You are probably one more victim of Pulseaudio's module `module-switch-on-connect`. He is the one setting `PulseEffects(mic)` as default device. And that is the reason why your volume keys are affecting PulseEffects sinks instead of the soundcard. 

I think that from version 17 onward Ubuntu started to load it by default. But only in Pulseaudio `12` `module-switch-on-connect` has become compatible with PulseEffects. If you can not upgrade to Pulseaudio 12 you will have to unload this module as explained at FAQ point `4`

**Comment by WarDogSniper** [comment]
Thanks you can consider this closed.  v12 pulseaudio (That I can find) is not ready for Ubuntu v18.04 just yet. (i'm on v11.1) I only did about 10 min of research so...
I will keep digging and maybe I will find an option but until then I will try the unloading module until then
Thanks again @wwmm !!!
