### ISSUE TITLE
Expose current preset in use

### ISSUE THREAD

**Issue by ejrees** [wwmm/pulseeffects#253]
I couldn't find any configuration location for the current preset in use. Is it possible to expose it via command line and make it persistent so it can interface with i3 status bars? Maybe also a default preset option that will be used on launch? As well as an "off" preset that is immutable.

**Comment by wwmm** [comment]
All PulseEffects options and parameters are saved in [gsettings keys](https://developer.gnome.org/gio/stable/GSettings.html) and can be edited in [dconf-editor](https://wiki.gnome.org/Projects/dconf):
![screenshot from 2018-06-28 21-57-39](https://user-images.githubusercontent.com/16225172/42067718-0d665d42-7b1e-11e8-9526-00c295c96b57.png)
There is no need for a default preset or an immutable off preset. GSettings remember the last value of every parameter. So when you reopen PulseEffects the last values used are automatically reloaded. In case you want to load a preset you made from the command line you can use one of the [command line options](https://github.com/wwmm/pulseeffects/wiki/Command-Line-Options) described in the wiki.

**Comment by wwmm** [comment]
I don't know what are `i3 status bars`. But third party code can tweak PulseEffects parameters in the same way dconf-editor does. You could do that from a python script for example

**Comment by ejrees** [comment]
yes I'm aware of the dconf settings, how can I access the config variable that lets me know which preset is currently active? I don't seem to see one.

**Comment by wwmm** [comment]
Now I understand what you want. Someone asked for this a long time ago. Unfortunately it is complicated to implement this in a consistent way. 

When you load a preset all that is done is telling gsettings to update every key with the values in the preset file. From gsettings point of view there is no difference between change a parameter manually using the interface controls or through the preset loading. As there is not an easy way to tell which was the reason why the parameter changed I can't just save the name of the last chosen preset. Let's say that for some reason the user changes one of the window controls. It is not his preset that is in effect anymore but something a little different he configured manually. So to be consistent I should reset the current preset name to an empty value. But as there is no easy way to tell if the key was changed manually or through a preset I don't have how to reset the preset name variable in a consistent way. 

Given the huge number of parameter in PulseEffects tracking this individually for each key would be insane. So this feature was never implemented.

**Comment by ejrees** [comment]
Thanks for the in depth reply. I'm not sure I fully understand, admittedly I haven't looked through the codebase just yet, but can you abstract the gsettings function so that on any change it will just clear the preset variable? Whenever you set anything you would just use the abstracted function, but when setting a preset you would do it directly.

**Comment by wwmm** [comment]
Too much work for too little gain. You will see that when you take a look at the code base. And I am not so sure we can abstract everything that would be needed to make this approach work. I am not using only the `set_double`, `set_int`, `set_boolean`, etc that you can see here [https://developer.gnome.org/gio/stable/GSettings.html](https://developer.gnome.org/gio/stable/GSettings.html). I also use the property bindings. Each control in the interface has a bidirectional binding to the corresponding gsettings key. They do not call the `set/get` functions in the api like it is done in the presets manager code. By doing this binding the key is updated when the control is changed and the control is automatically updated when the user changes the key using third party softwares like `dconf-editor`. All of this is done with just one function call to do the binding. GSettings does all the rest. No need to write any additional code.

There are a few other difficulties too. Each xml file you can see here [https://github.com/wwmm/pulseeffects/tree/master/data/schemas](https://github.com/wwmm/pulseeffects/tree/master/data/schemas) represents one of the gsettings databases used in PulseEffects. Each plugin has its own database. The interaction with all of them would have to be abstracted. It is not a small refactoring. To complicate things even more in some places I had to talk directly to the C api because GTKMM did not have the necessary C++ wrapper. So this abstraction would have too take this into account too. And to be honest I don't know if I want to complicate the code base even more by adding these abstractions... At the end of the day PulseEffects is still a one man job...

Considering that other people would like to have this feature too (myself included) I think that we will have to forget consistency. It is quite easy to save the preset name in a gsettings key whenever the user loads a preset. But resetting it or not depending on user interaction with the window isn't. At least not without rewriting a lot of code. So my suggestion is that we just save the name and update the button label accordingly at PulseEffects start. It would be up to the user to remember that once he/she touches any control that preset shown in the button label (and saved in a gsettings key) makes no sense anymore. In a way this variable would represent the last used preset but not necessarily the current settings in use. I think we can live with that.

**Comment by wwmm** [comment]
I implemented the simple "solution" I described above in the latest master code. The key is named `last-used-preset` and can be found here [https://github.com/wwmm/pulseeffects/blob/05d756b01a904173f8cdaebe8611ec89d39e4151/data/schemas/com.github.wwmm.pulseeffects.gschema.xml#L182](https://github.com/wwmm/pulseeffects/blob/05d756b01a904173f8cdaebe8611ec89d39e4151/data/schemas/com.github.wwmm.pulseeffects.gschema.xml#L182)

You can read this key from command line executing `dconf read /com/github/wwmm/pulseeffects/last-used-preset`.
