### ISSUE TITLE
Titlebar and tiling WMs

### ISSUE THREAD

**Issue by Sigma-One** [wwmm/pulseeffects#258]
Now I will say this right away, I don't know anything about how this is written, so this may or may not be even possible.

The application works perfectly in i3wm, but a minor annoyance is the fact that it still uses a GNOME-style titlebar with window controls integrated into it, which looks a bit off when everything else has no titlebar at all, or no window controls, depending on the configuration.

An option to hide the controls, or even better, use decorations provided by the WM, would be a good thing to have for situations like this, especially if you want the application to feel well-integrated in as many environments as possible.

**Comment by wwmm** [comment]
PulseEffecs uses gtk headerbar and client side decoration. I have no intention to change that. So from PulseEffects code point of view using WM decorations is not an option. This will have to be done by some kind of integration at GTK and WM level. I think KDE has something like this

**Comment by ex47** [comment]
@Sigma-One devilspie2 can remove decoration

**Comment by r-o-o-t-y** [comment]
my two cents

there are a number of roundabout ways to get it to look decent (if you tweak kwin to force the window title, then remove the window title with breeze, that is if you use breeze... or this gtk3-nocsd package that makes it look presentable) but no, officially GTK3 CSD is not supported in KDE because it's so far been incumbent on the GTK developers to incorporate the patches that the kwin team has submitted to them, and they're apparently _not very amenable to the idea_ (while on the flipside Qt applications are fairly easy to integrate into GNOME)

**Comment by flipwise** [comment]
Actually, I've found a hack to get rid of the GTK title: https://github.com/PCMan/gtk3-nocsd/issues/19

**
![image](https://user-images.githubusercontent.com/26850445/42473870-ba29071c-83bd-11e8-938b-ef4d927a34a5.png)
**

Blends in perfectly into KDE now and restores KWin's control over the window, along with the incompatible features such as shadows and modifiable borders.

**Comment by r-o-o-t-y** [comment]
props
