### ISSUE TITLE
appdata changelog language strings

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#322]
Why do we need changelog language strings in po files?

E.g.
```
#: data/com.github.wwmm.pulseeffects.appdata.xml.in:452
msgid "Performance issues with service mode and slower CPU's"
msgstr ""
```

They don't really need to be translated, it's a waste of resources and junk for PO files, I think.
Where do users see theese changelogs? Do gnome-software and other software which parse appdata show these changelogs?

@AsavarTzeth please have a look at this.

**Comment by wwmm** [comment]
`ninja pulseeffects-pot` added them. I imagine that they should be marked as `untranslatable` for this not to happen

**Comment by AsavarTzeth** [comment]
How do you mean, it a waste of resources? Junk? Sorry but that is not a reasonable technical argument; people will never read the finished file directly. Still, I do agree that it is a waste of human resources (if that is what you meant).

Front-ends like GNOME Software do use this to present changes before you accept updates, However at this time that is unlikely to work for pulseeffects. For it to work you would have to use a string freeze period, prior to release.

Currently, these strings are pretty much impossible to translate in time, since you would update the appdata and then tag a release immediately after.

I also don't think Flathub supports multiple languages, so currently it would only be shown in English there anyhow.

Now the question is if and how these can be marked as untranslatable. I could certainly look into it.

**Comment by mikhailnov** [comment]
Yes, I meant it's near to be a waste of human resources to translate changelogs.
And having a lot of language strings which will never be translated does not help to concentrate on translating the main parts.

**Comment by mikhailnov** [comment]
How is changelog in `data/com.github.wwmm.pulseeffects.appdata.xml.in` formed? By hands copypasting from CHANGELOG.md?

**Comment by AsavarTzeth** [comment]
Well then I have some good and bad news.

I did find a way to disable what we want, so that it won't be added to `pulseeffecta.pot`.

However there seems to be an issue with meson or xgettext, that prevents me from overriding the defaults.

Yes, you would have to add anything under `<descriptions>` manually. The helper script just enables @wwmm to easily add the minimum required data.

**Comment by AsavarTzeth** [comment]
Also, as discussed earlier, simply copy/pasting from `CHANGELOG.md` is not a good idea.

You can use it as a source but some things might require adjustments.

**Comment by wwmm** [comment]
Honestly I am fine with removing all the descriptions and keeping only version and dates. Once there is a good way to disable the translation we could reconsider to add changelog messages in the appdata

**Comment by AsavarTzeth** [comment]
That is a solution too, and a much simpler one. I could do that as a temporary workaround.

If there is a bug in meson, or whatever, we would likely have to wait for quite some time anyhow.

**Comment by wwmm** [comment]
That is what I am thinking. Requiring a very recent meson version just for that is unnecessary in my opinion.
