### ISSUE TITLE
Orange triangle with exclamation mark

### ISSUE THREAD

**Issue by pstngh** [wwmm/pulseeffects#349]
Hi,

on my setup, the limiter on the left pane keeps alternating between the white checkmark to the orange triangle. does that represent an error? or just that it's applying changes to the output?

Thanks

**Comment by wwmm** [comment]
It is not an error. This means that the limiter input is saturated (the input signal intensity is above 0 dB). In the other plugins this would be a problem because signal clipping can happen above 0 dB. In other words distortion your audio would be distorted in a way that you can hear the noise.. But the limiter can deal with strong signals in its input. You have to pay attention if the exclamation mark is being shown for the other plugins

**Comment by wwmm** [comment]
This information can be found in PE help
![screenshot from 2018-10-06 14-58-02](https://user-images.githubusercontent.com/16225172/46574371-48d55880-c978-11e8-88da-1dfab60bdd46.png)

**Comment by pstngh** [comment]
Ok thank you, just a question, since the limiter's goal is to limit the sound, it's always going to be saturated right? so it doesn't mean anything is wrong with my preset, just that the limiter will always show the saturation warning once the input reaches the "limit"

**Comment by pstngh** [comment]
Thanks!
