### ISSUE TITLE
Pitch effect

### ISSUE THREAD

**Issue by capricorn86** [wwmm/pulseeffects#36]
Thank you for all the work you are doing with PulseEffects, it is a nice application.

Functionality like pitch would be a nice to have feature in PulseEffect, so that it is possible to manipulate a voice live for example. I would personally mostly be using it during Skype calls as a fun feature when talking to friends etc.

**It seems like this GStreamer plugin supports pitch:**
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-plugins/html/gst-plugins-bad-plugins-plugin-soundtouch.html

**This is a Python wrapper for it:**
https://github.com/jrising/pysoundtouch

I am however not sure if it is possible to use it live.

**Comment by wwmm** [comment]
I think it can be done in realtime. Now what we have to think about is the place in the effects chain to put it and how to expose it in the interface. I think that in order to save space in the interface this plugin could be added to a popover menu as an "output filter" or "input filter" of one of the plugins already in place like I am already doing with the highpass and lowpass plugins before the equalizer. 

Another important point is if it is possible to adjust the pitch controls so that there is no effect applied. Like "no reverb", "no compression", etc. Right now there is a limitation in PulseEffects that no plugin is really disabled. Doing this would require to remove the plugin from the pipeline in realtime. It is possible but I would have to add lots of code to cover all the possible combinations of plugins turned on and off.

**Comment by Bleuzen** [comment]
@wwmm What about it now? ;)

**Comment by wwmm** [comment]
Hi! Latest master has the pitch shifting plugin from [rubberband](http://breakfastquay.com/rubberband/). If everything goes well in the next 2 or 3 days I will release PE 3.1.7

**Comment by Bleuzen** [comment]
Ok :D
I think we can close this now.
