### ISSUE TITLE
Stuttering with Spotify and Twitter

### ISSUE THREAD

**Issue by Deividhp13** [wwmm/pulseeffects#362]
Hello, I have a problem. When i have Spotify enable in PulseEffects, and also the Firefox (AudioIPC Server), every time a Twitter video loads I hear a noise and the music is faster or slower and choppy for half a second or so. I'm on Manjaro with KDE. 

EDIT: When I disable PulseEffects in Spotify, and leave it with the Internal Audio option, the sound is perfect. So that's why I think the problem is related to PulseEffects.

**Comment by wwmm** [comment]
I can hear something like this sometimes when a second audio source like mpv is started. This may have the same source as #350. The problem is that the source of the problems in #350 is a Pulseaudio bug that nobody is looking at right now.

Unfortunately I do not see much I can do about this stuttering from my side. All I do in PE is telling GStreamer and Pulseaudio to do their work. Maybe if you play a little with the buffer and latency parameters the stuttering will be less noticeable. But I doubt it would fix it.

**Comment by Deividhp13** [comment]
Yes, you're right. I made some tests with another equalizers and the problem is always the same, so it's a Pulseaudio bug for sure. Thanks for the reply :) and thanks for Pulse Effects too, it's amazing.

**Comment by wwmm** [comment]
The fix for #350 should work here too
