### ISSUE TITLE
No visualizer and effects.py

### ISSUE THREAD

**Issue by DroWnThePoor** [wwmm/pulseeffects#39]
This is on ElementaryOS 0.4 (Ubuntu 16.04)
Not sure what's causing the 'magnitude' error.
My visualizer/spectrum doesn't show anything which I think is tied to GstValueList error as it appeared when enabling spectrum.

File "/usr/local/lib/python3.5/dist-packages/PulseEffects-2.0.3-py3.5.egg/PulseEffects/sink_input_effects.py", line 410, in on_message_element
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList

**Comment by Ixoos** [comment]
I have the same problem, I'm using newest version of pulseeffects on fedora 26.

**Comment by wwmm** [comment]
You need gstreamer 1.12 or above. The type GstValueList is not implemented in older versions

**Comment by BurningTreeC** [comment]
installing python3-gstreamer solved it for me

**Comment by Ixoos** [comment]
Same for me, now everything works <3.

**Comment by DroWnThePoor** [comment]
Unfortunately I can't seem to find that package in Ubuntu's repos..
pip shows nothing that satisfies my distributions requirements and apt shows:
python3-gssapi       python3-gst-1.0      python3-gst-1.0-dbg  python3-gsw 
And the actual gstreamer packages seem to only go to 1.0. I was thinking about trying to compile 1.12 from source, but now there's this python3-gstreamer library. So I'm honestly not sure where I should go from here.

**Comment by JackHack96** [comment]
The only way for using newer PulseEffects versions on Ubuntu (even 17.04), you first need to upgrade GStreamer from 1.10 to 1.12. I have the same problem (I use 16.04 on my main machine and 17.04 on my second PC, both use GStreamer 1.10). When I'll have some spare time, I'll try to upgrade GStreamer and if I succeed to make PulseEffects running, I'll make a wiki page documenting the process ;)

**Comment by wwmm** [comment]
I didin't imagine that the moving pulseeffects to gstreamer 1.12 would cause so much problems for people using non rolling release distros :( Before 1.12 we needed a hack to access gstreamer spectrum magnitudes from Python. A few types like GstValueList were not exposed in gst-python bindings. Gstreamer developers fixed this in version 1.12 and I decided to take away that ugly and slow hack from PulseEffects code.

**Comment by dx9s** [comment]
@wwmm fully understood. Rolling releases are always 'more' bleeding edge and potentially unstable, slower releases (Ubuntu LTS) tends to see PPAs for things that are stable enough and newer. AS a developer, you want to have all the new stuff (I fully understand that) but at the same time the target market has to wait (several years at least) to catch up when on something like an LTS. Upgrading from source is possible, but ugly. Myself, I *try* to shoot for the lowest common 'reasonable' denominator. If it is solved in upgrading to non (Ubuntu) LTS, that might be 'reasonable' to you. For myself, I try to stay with LTS for work reasons (servers I manage, etc.).

**Comment by dx9s** [comment]
FWIW. I and 16.04 LTS and have everything except the RTA working, reverberation seems to work. It's a good enough compromise for now (see other issue I commented on upgrading using pip3 to solve that Curve problem). Just figured I'd see and find/comment on the RTA issue.

**Comment by AsavarTzeth** [comment]
Well some good news on this topic. For those that care, I recently finished a [Flatpak](http://flatpak.org) version of PulseEffects, which is currently going through testing on [Flathub](https://github.com/flathub).

It works very well on both my Arch Linux and Ubuntu LTS machines.

**Comment by wwmm** [comment]
Thanks @AsavarTzeth :-) I considered learning how to build a Flatpak package sometime ago but I didn't  have the time.

**Comment by Fritigern** [comment]
Kubuntu 17.10 Artful Aardvark here. I too lack the spectrum visualization and my GStreamer1.0 version is 1.12.2. 
I updated Pulseeffects to make sure that I have the latest which currently appears to be 2.3.1.
And as someone earlier in this topic mentioned, Ubuntu does not have python3-gstreamer in its repos nor anything similar.

It would be nice if a solution could be found for this. Thanks in advance!

**Comment by wwmm** [comment]
Hi. I am surprised that the spectrum is the only thing not working. PulseEffects is a Python 3 application and in order to interact with Gstreamer it needs the gst-python bindings [https://github.com/GStreamer/gst-python](https://github.com/GStreamer/gst-python). Nothing works in PulseEffects if none of the files of gst-python are installed.

As you have Gstreamer 1.12.2 and only the spectrum is not working Kubuntu must be including part but not all of gst-python inside the order gstreamer packages.

**Comment by wwmm** [comment]
Hi. I am surprised that the spectrum is the only thing not working. PulseEffects is a Python 3 application and in order to interact with Gstreamer it needs the gst-python bindings https://github.com/GStreamer/gst-python. Nothing works in PulseEffects if none of the files of gst-python are installed.

As you have Gstreamer 1.12.2 and only the spectrum is not working Kubuntu must be including part but not all of gst-python inside the order gstreamer packages.

**Comment by wwmm** [comment]
I decided to uninstall gst-python and indeed everything works but the spectrum... This is so bizarre =/

**Comment by wwmm** [comment]
Without gst-python installed PulseEffects prints in the terminal the error `TypeError: unknown type GstValueList`. This is the same error that will be printed by an older Gstreamer even if gst-python is installed. 

In any case the real solution here would be to have gst-python in Kubuntu's repository

**Comment by wwmm** [comment]
Did you try this package ? [https://packages.ubuntu.com/artful/python3-gst-1.0](https://packages.ubuntu.com/artful/python3-gst-1.0)

**Comment by AsavarTzeth** [comment]
If you are interested I might have solved the same, or a similar, issue in my Flatpak.

For the longest time I were so confused why it acted like I had an older version of Gstreamer (and the bindings) when I had built all the latest from source.

The Gnome 3.24 runtime also include an older version of gstreamer and gst-python. In my case they could not be removed, because the runtime is read-only to the app.

It took a really really long time to understand the issue and figure out a solution, but I did it in the end. It is kind of a hack but it works.

See the commented lines:

- https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json#L21
- https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json#L277

**Now the really good news.**

The latest version of PulseEffects is now available on (Flathub)[https://flathub.org] so regular users don't have to handle this issue anymore.

**Comment by AsavarTzeth** [comment]
Oh and if that is not the issue, I would double check that your gst-python version is built for python3. Remember that a lot of distributions still default to python2.

For example the packages in Arch Linux are named:
- `gst-python` (python3)
- `gst-python2` (python2)

In Ubuntu they are still named:
- `python-gst` (python2)
- `python3-gst` (python3)

If you installed the wrong one it might as well not be there at all.

**Comment by Taubaurt** [comment]
Yes! It works perfect for me using the Flathub package. Ty so much.

**Comment by wwmm** [comment]
As we have a flatpack package and there is nothing I can do about missing dependencies in ubuntu I will close this issue. Feel free to open another one in case you need further help
