### ISSUE TITLE
Tune music to 432 Hz

### ISSUE THREAD

**Issue by tmiland** [wwmm/pulseeffects#41]
Hi, 

it it possible to tune the output music to 432 Hz, instead of 440 Hz?

If so, how could this be achieved? If not, is that something that can be integrated in to the app?

I have been looking for a solution to do this for so long now, and there is only methods for playing music files, not streaming services like Spotify etc...

Best regards,
Tommy :)

**Comment by wwmm** [comment]
Hi

I am not sure I understand. By tuning you mean to have a equalizer band centered at 432 Hz or to be able to generate a test signal at 432 Hz?

**Comment by tmiland** [comment]
Hi, thanks for answering.

Have the equalizer band centered at 432 Hz, preferably with an option to choose between the two maybe?

Read about it here: https://en.wikipedia.org/wiki/Concert_pitch

Most music is tuned to 440 Hz, and the question is to tune it to 432 Hz. :)

**Comment by wwmm** [comment]
Right now there is no way to change the center frequency and the bandwidth of the equalizer. So it is not going to be possible.

Though I am using Gstreamer's parametric equalizer under the hoods I am just using its default values for center frequency and bandwidth. I am not setting these values or exposing their controls anywhere in PulseEffects because I was more interested in having a 15 bands graphical equalizer than a parametric (and being honest I do not know how to properly use a parametric equalizer in all its glory XD).

In other to properly support this feature I would have to expose all Gstreamer's parametric equalizer controls in PulseEffects interface. What will not be easy considering how crowded the interface already is... It would probably be a good idea to support presets for these controls too, etc... It is possible but will require some work...

I will give some thoughts to this... Lets keep this issue open for now in case other users are interested in having full control over the parametric equalizer.

**Comment by tmiland** [comment]
I understand. Take your time. I know that your app would gain an immense amount of popularity if you where able to achieve this, as more and more people realize it's time to shift back to 432 Hz.

Spotify, or any other streaming provider has not been willing to do this, so imagine the potential at your fingertips. :D 

I just found your app, and it was the first thing i thought about. Great job btw. :)

Best regards,
Tommy

**Comment by wwmm** [comment]
Hi. Equalizer frequencies and quality factors can be tweaked in latest PulseEffects(2.3.0)
