### ISSUE TITLE
Audio source information

### ISSUE THREAD

**Issue by marcscama** [wwmm/pulseeffects#413]
Hi,
it's possible to KNOW the information of audio source like:bitrate, HZ, codec etc...
because the data information on the top on app it's not clear.
thanks

**Comment by wwmm** [comment]
The information in the headerbar is about the processing stages inside PulseEffects
![screenshot from 2019-01-13 17-08-54](https://user-images.githubusercontent.com/16225172/51089533-f74a2000-1755-11e9-8786-cce52bc00458.png)

Information about each audio application can be ssen in the apps section
![screenshot from 2019-01-13 17-10-08](https://user-images.githubusercontent.com/16225172/51089548-2e203600-1756-11e9-9dfb-faf34a60e3c2.png)

Information like bitrate and codec can not be displayed because audio processing can only be done to raw audio samples. By the time the audio gets to Pulseaudio it is already raw. Only information like sampling rate and bit format remains. But these ones are already shown in the apps section
