### ISSUE TITLE
EQ does nothing...?

### ISSUE THREAD

**Issue by sidbmw** [wwmm/pulseeffects#440]
Updated pulseeffects a couple hours back on Manjaro Linux (Gnome) and nothing pulseeffects seems to have no effect on the audio.

The little graph at the bottom of the EQ which should the input and output decibel? (volume? idk) does not display anything and moving the EQ sliders up and down have no effect either.

Any ideas?

**Comment by wwmm** [comment]
You probably don't have the package `lsp-plugins` installed. The new PulseEffects version needs it for the equalizer

**Comment by sidbmw** [comment]
Yep, I was able to fix that yesterday night. The EQ settings seem to be different this time though. I used to be able to crank 23-45Hz to +12 and get my desired EQ. When I do the same now...it sounds really bad. How do I set it up like my old one?

**Comment by wwmm** [comment]
The new eq uses different filters. So some tuning will be needed. The old eq had width as main parameter. The new one uses the quality factor as the majority of eqs out there. So you have to adjust the quality so that the width is close to the one you had before.

Were you using low shelf mode in this band? As you can see here #421 the old equalizer had an odd behavior in this filter.

**Comment by sidbmw** [comment]
I have no idea what the filters do lol... I just used the default on the old version.

**Comment by hpg-mheck** [comment]
Has anybody had any luck getting the filters to actually do anything on Fedora?  I have installed from source after making sure all even vaguely-desired optional prerequisites were fully installed.  It seems to route audio, but none of the filters have any effect whatsoever, no matter what.  The main amplitude slider works, though, and turning applications on and off results in a large amplitude change.
