### ISSUE TITLE
Ability to modify bin frequency values for equalizer

### ISSUE THREAD

**Issue by cdbrendel** [wwmm/pulseeffects#46]
It'd be great to have a functionality where the specific frequency values can be set for each "bin" (slider) in the equalizer pane (e.g. changing "26Hz" for first slider to "30Hz" or something). I'm not sure if this is possible (or if the functionality already exists but I'm not seeing it), but it would be handy for people using specific profiles created for other equalizers for specific audio equipment.

**Comment by wwmm** [comment]
Hi. At this moment this is not possible but I will think about it. The main issue is how to expose this in a interface that is already a little crowded. Specially because when changing the center frequency it will probably be necessary to adjust the bandwidth also. So the width control should also be exposed.

**Comment by dx9s** [comment]
I would be happy with a typical 7-band ISO centered frequencies ( 63, 160, 400, 1k, 2.5k, 6.3k, 16k ) -- that would free-up / simplify UI interface. A side option would be to put in a steep 24db/octave (https://en.wikipedia.org/wiki/Linkwitz%E2%80%93Riley_filter#Fourth_order_Linkwitz.E2.80.93Riley_crossover_.28LR4.2C_LR-4.29 -- LR4) that is adjustable/bypass-able up to whatever frequency (although I'd use it up to 20-40Hz typically to remove energy that usually just distorts HF output under certain conditions).

**Comment by dx9s** [comment]
Note, the 'labels' versus the actual frequency can differ. i.e. label is 400hz but the math behind setting up that band can still be 410Hz. That is common in many products (DSP based active crossovers/EQs/etc).

**Comment by wwmm** [comment]
Using 7 bands would save space in the interface but I started with 10 and moved to 15 because I wanted a more fine grained control. 

There is a high-pass and a low-pass in PulseEffects with adjustable frequencies but I don't think that they that steep. If you know a stereo gstreamer or ladspa plugin that is steeper and typically available in distributions repositories I could switch to it.

**Comment by wwmm** [comment]
Hi. I added the hability to change frequencies and quality factors to latest PulseEffects(2.3.0)
