### ISSUE TITLE
What does the ! symbol mean?

### ISSUE THREAD

**Issue by ptkato** [wwmm/pulseeffects#485]
Also, sometimes it flickers, changing between ! and ✓.

![image](https://user-images.githubusercontent.com/10677806/56005612-a8098200-5ca7-11e9-9f7f-96f130cae1b5.png)

**Comment by wwmm** [comment]
It means you are saturating the plugin input
![Screenshot from 2019-04-12 00-36-41](https://user-images.githubusercontent.com/16225172/56010693-0ee46680-5cbb-11e9-947f-ab6a2e2987ce.png)
This is something you want to avoid. Otherwise you will have audio clipping https://en.wikipedia.org/wiki/Clipping_(audio). Try to reduce your audio app volume or use the plugin input/output gain
