### ISSUE TITLE
command line options/open pulseffects with processing enabled

### ISSUE THREAD

**Issue by 9oLHhgeK** [wwmm/pulseeffects#51]
I have the program set up to launch automatically at login though I find I have to enable it using the bottom right toggle. Is there a way to launch it with its default state being enabled?

**Comment by wwmm** [comment]
At this moment it is not possible. I am not sure it it is a good idea to do that in pulseeffects because pulseaudio already tries to remember applications last used sink. I have to think if there would be any kind of conflict and in case there isn't what would be the best way to implement this feature.

**Comment by wwmm** [comment]
For now I will rely on Pulseaudio for that as version 11 seems to do a much better job at remembering applications last used sink
