### ISSUE TITLE
pulseeffects freezes when there is no pulseaudio

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/pulseeffects#511]
Tried to run PulseEffects in chroot, there was no PulseAudio running
```
# G_MESSAGES_DEBUG=pulseeffects pulseeffects
(pulseeffects:79): pulseeffects-DEBUG: 05:37:49.910: application: PE version: 4.6.0

(pulseeffects:79): GLib-GIO-CRITICAL **: 05:37:49.913: g_dbus_connection_signal_subscribe: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(pulseeffects:79): GLib-GIO-CRITICAL **: 05:37:49.914: g_dbus_connection_call_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
(pulseeffects:79): pulseeffects-DEBUG: 05:37:49.915: pulse_manager: context is connecting
(pulseeffects:79): pulseeffects-DEBUG: 05:37:49.915: pulse_manager: failed to connect context
```

it froze, ctrl+c did not stop it, only ctrl+z and `kill -9` could stop frozen pulseeffects

**Comment by mikhailnov** [comment]
it would be nice to be able to reliably understand from https://github.com/wwmm/pulseeffects/blob/master/util/test.sh#L86 if Pulseeffects is running or not, here it it running but frozen.

It's not an important issues, however, may be we have even discussed it before.

**Comment by wwmm** [comment]
It freezes because we have to wait for the connection to Pulseaudio to be finished before going to the next steps https://github.com/wwmm/pulseeffects/blob/10342e6aa4724e81334c8c47fe44e4bbd31d1691/src/pulse_manager.cpp#L16. If we do not wait lots of things will be broken.

I think that we will have to use two definitions of running in these tests.. One thing is having the window open and all initialization done. Another thing is having our GStreamer pipeline running. The effects pipeline will not run if the first round of initialization fails. But everything else can be ok and the pipeline may not run for its own reasons.

In any case I think that searching for `PulseEffects_apps` in the output of the command `pactl list sinks` is reasonable way to externally check if the first the first round of initialization worked. If our sink was loaded probably all the other interaction with Pulseaudio worked too.

**Comment by wwmm** [comment]
Obviously `pactl` will only be available and functional if Pulseaudio is installed and running.

**Comment by smac89** [comment]
I recently created a systemd service that automatically starts pulseeffects and also restarts it when pulseaudio is restarted:

```
[Unit]
Description=Pulseeffects service
PartOf=pulseaudio.service
After=pulseaudio.service

[Service]
ExecStart=/usr/bin/pulseeffects --gapplication-service
SyslogIdentifier=pulseeffects
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
```

Also useful for starting pulseeffects because it will wait for pulseaudio before starting it

**Comment by wwmm** [comment]
Interesting! :-)

I will close this issue. The only benefit I see of not "freezing" when Pulseaudio is not running is showing the window. But as this windows will not be functional without Pulseaudio there isn't much point. And the amount of code refactoring necessary to achieve this is considerable...
