### ISSUE TITLE
[Help] Listing presets from the command line

### ISSUE THREAD

**Issue by csehszlovakze** [wwmm/pulseeffects#517]
The wiki says to -p option the following:

>They are printed to the system log as all other PulseEffects messages

Where can I find this log? (Kubuntu 18.04.2) Also, why doesn't PE print the preferences to standard output when invoked with -p?

**Comment by wwmm** [comment]
Now that you asked about it I noticed that this is not working as i should. There is a bug and a limitation I am not sure how to fix. As things are right now this option only prints the presets list when PulseEffects is executed in debug mode. And even this way it will only be visible if you do not have another PulseEffects instance running in background. What most users will have =/. When this option was added we did not have the ability to run as a service...

Making these messages to be printed without the need to be in debug mode is easy. But I don't know how to make them visible when we have an instance in background. GTK redirects the output to the place where the background instance is printing...

PE doesn't print preferences with -p because there never was a need for that. And because there will be tons off them. Is there something you have in mind?

**Comment by csehszlovakze** [comment]
>PE doesn't print preferences with -p because there never was a need for that. 

Presets, not preferences. I'm asking because if it worked, I could write a script to query the presets, create a systray icon which lists them and on click it'd switch to that preset without ever opening the main window by passing that preset with -l (I run PE as a service all the time).

**Comment by wwmm** [comment]
Ok. I will try to improve this. The code in master branch is already able to print without being in debug mode. But as I am running PE in service mode when I run `pulseeffects -p` in a terminal GTK redirects the output to the background instance and the list has to be seen using `journalctl -b`. In short, it wasredirected to the system log =/ There are cases where this is exactly what I want GTK to do. But when listing presets this is really undesirable =/

**Comment by wwmm** [comment]
Until this is better you can read the files in these paths
```
~/.config/PulseEffects/input/
~/.config/PulseEffects/output/
```

this is where presets for input and output  devices are saved and I don't have a reason to change these paths in the next PE versions.

**Comment by wwmm** [comment]
I found a way to fix this. We have to define a G_APPLICATION_HANDLES_COMMAND_LINE callback to handle local command line options separated from the others. Now it is working as it should. The output is like this
```
wallace@wwmm ~/myfiles/code/cpp/pulseeffects/_build/src $ ./pulseeffects -p
Output Presets: mrodd,game,movies,music,twitch,none,
Input Presets: c-1u mic,none,
```
Master branch was updated with this fix.
