### ISSUE TITLE
Add an option to disable individual effects

### ISSUE THREAD

**Issue by Bleuzen** [wwmm/pulseeffects#52]
Currently all effects are always enabled.
This causes more CPU usage as needed. On my old laptop this is bad, also for the battery..

So it would be great if we could enable for example only the equalizer, if we only need the equalizer.
This would also 'fix': https://github.com/wwmm/pulseeffects/issues/42

For the GUI: What about something like 'planes' or 'tabs' ..
I mean there could be a effect list at the left and right of it there can be the effect settings.
Depending on which effect is selected in the list at the left, the settings things change at the right..

Like this for example:
![pei](https://user-images.githubusercontent.com/12885163/29240657-de1308fc-7f69-11e7-869d-2317d8ab4716.png)

At the left, (in the effects list), currently "Equalizer" is selected and next to the list, there are the equalizer settings (marked orange) with an "enable" checkbox.

With this GUI, there would be also more place for the effect settings, because always only the settings of the current selected effect of the list are displayed.

(I know, not the best example picture and maybe not the best idea in general, but I have no other idea yet.)

Maybe this is the next big goal for 3.0 and it would be great ;)

**Comment by wwmm** [comment]
Hi @Bleuzen 

I totally agree with you that it would be great to be able to enable/disable plugins. I wanted this since the beginning. But unfortunately it is ridiculously complicated to to that. Gstreamer plugins do not have a enable/disable switch. In other to do that we have to remove the plugin from the pipeline and rebuild the connections. And there are many possible combinations to take into account. For example if the user disable the reverb I have to connect the compressor level meter output to the equalizer preamp input. Now if the input limiter is disabled I have to connect pulsesrc output to the compressor inputand so on. I would have to add so many code to take all the possible combinations into account that I gave up.

I will think about the possibility of using a gui with tabs for the effects. I really like to see all the levels at the same time but using tabs would give a much needed space for the addition of other controls or plugins. Specialy now that people are asking to have control over the equalizer frequencies.

**Comment by Bleuzen** [comment]
Ok,
1. Are the input and apps effects both always enabled? If yes, can you add an option to enable / disable the effects for input / apps sink?
So that we can disable the input devices effects for example if it is not needed.
This should lower the CPU usage already a little.

2. I guess the equalizer is the most used / needed effect.
So maybe you can implement an "equalizer only" mode.
(a switch .. between "all effects" and "only equalizer"..?)

With this option, people could decide if they only need the equalizer, but not the other effects (like me on my old laptop) and want to lower CPU usage
OR
If they have a good CPU (and are not on a battery hungry old laptop) and need all the effects of PulseEffects.

**Comment by wwmm** [comment]
1. The app effects pipeline is on the playing state only when there is an app listed at the bottom of PulseEffects window. The same goes for the input effects. They are enabled only when an application is recording sound.

2. This would easier but will still require a lot of work. I will think about it.

Are you running directly from the source? If yes could you edit the file `sink_input_effects.py` and change the value of the variable `self.spectrum_nbands` at line `51` to something smaller than 1600? Can be something like 400 or 100. In order to have better resolution at the lower frequencies of the spectrum I am using a high number of frequency bands to calculate the fast fourier transform. And for the reasons I explained in the last post this calculation is done even when the spectrum is not shown in the interface. In my Ryzen 1700 the cpu use in gnome system monitor stays under 1% but maybe this isn't the case in older CPUs.

**Comment by Bleuzen** [comment]
I was not running from source, I use the AUR package, but I downloaded the code for testing and changed spectrum_nbands to 400 and 100.
CPU usage of PulseAudio when playing went from ~18% to ~16%, so this doesn't change much.

On my main PC, Pulseeffects uses ~6% CPU during mic and output effects are enabled.
This is still much for just an Equalizer (as I said, I don't realy need the other effects).

So an Equalizer only mode would still be great ;)

**Comment by wwmm** [comment]
Hi. Latest PulseEffects has a new interface using gtk stacks. No idea when or if the on/off switches will be implemented.

**Comment by Bleuzen** [comment]
On/off switches for all effects would be realy cool, but I don't need it necessarily. Maybe this will be a thing for the future or never be implemented. Ok.

I know, I cannot and don't want to force you, but an Equalizer only mode would be enough for me and it would be realy nice, if you could implement this.
I'm searching for a simple Equalizer for Linux for In-/Output for a long time. PulseEffects can do this and is nearly perfect, but it uses too much CPU (because of Effects I don't need?).

Please think about this ;)

**Comment by wwmm** [comment]
Today I released PulseEffects 3.0. Now we can enable/disable all plugins. The magic was possible thanks to the container GstInsertbin. It does most of the hard work necessary to deal with dynamic gstreamer pipelines.

**Comment by Bleuzen** [comment]
Thanks, works great for me :D
