### ISSUE TITLE
Default release for Maximizer

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/pulseeffects#521]
Hello, I played around with Maximizer. First times I did it release unit was wrong, it was reported in seconds. I didn't know what was it's meaning (neither now in reality), so I didn't touch it thinking that since it was the default, it was the best setting for the plugin. Meanwhile, in the next releases unit size was fixed in ms, I know this doesn't change nothing in the plugin itself taking always the same default value. 

Anyway I went in its [source code](https://github.com/zamaudio/zam-plugins/blob/af338057e42dd5d07cba1889bfc74eda517c6147/plugins/ZaMaximX2/ZaMaximX2Plugin.cpp#L34) and discovered that the default value it's not 3,16 ms as reported in PulseEffects, but 25 ms and it's range is from 0 to 100 ms.

So I played with it other times and discovered that with the highest release value (100 ms) there's no distortion at all, even setting the plugin at stronger parameters, i.e ceiling -20 db and threshold -30 db.

Since in the source code there's 25 ms as default for release parameter, I think it should be the same for PE. And I see that the plugin has also other two parameters not shown in PE, Gain Reduction and Output Level. I wonder why these are not exposed. I think they are just like Pre-Amplification and Makeup in the Compressor, but they could be also showed for Maximizer.

In the end I think this is the best plugin, it's unbelievable that it could play as a limiter, an upward compressor, a downward compressor and a gate all in one module with very few parameters and at highest release there's no sign of distortion. Maybe I won't use it because it's very strong in the compression stage (the compressor can be tweaked to do a smooth compression), but it's a very useful plugin.

**Comment by wwmm** [comment]
Thanks for the hint! I don't know I never thought about taking a look at its sources. I will update the value to 25 ms.

The reason why `3,16 ms` has been used is because that is the value GStreamer is reporting as default. Run the command `gst-inspect-1.0 ladspa-zamaximx2-ladspa-so-zamaximx2`. In its output we have
```
release : Release
               flags: readable, writable, controllable
               Float. Range:               1 -             100 Default:        3,162278
``` 
The command `analyseplugin /usr/lib/ladspa/ZaMaximX2-ladspa.so` also reports `3,16` as default. But now I see that in the file `/usr/lib/lv2/ZaMaximX2.lv2/ZaMaximX2_dsp.ttl` `25 ms` is used as default. So what is happening is that the LADSPA insterface of the maximizer reports `3,16` and the LV2 interface is the one reporting `25`. As Zam plugins LV2 variant do not work in GStreamer and I have to use it through LADSPA I never noticed this.

**Comment by wwmm** [comment]
Fixed in `4.6.3`

**Comment by Digitalone1** [comment]
Thanks @wwmm  

What about Gain Reduction and Output Level parameters? Will you expose them?

**Comment by wwmm** [comment]
I can expose them. I am not sure why I did not do that. I must have forgotten XD Please open another issue so I remember to do that before the next release.
