### ISSUE TITLE
Vivaldi browser: incorrect icon

### ISSUE THREAD

**Issue by csehszlovakze** [wwmm/pulseeffects#529]
Instead of its proper icon, Vivaldi has a Chromium icon on the applications tab.

![Screenshot_20190614_090916](https://user-images.githubusercontent.com/50457795/59490271-7e75fe00-8e84-11e9-83df-b77f4ba76978.png)

Version: 4.6.3 on Kubuntu 18.04.2

**Comment by wwmm** [comment]
This is probably a Vivaldi bug. We do not search the system for each app icon. We ask Pulseaudio which is the value of the property `application.icon_name` that the audio app has reported to it. PE is showing chromium icon because Vivaldi told Pulseaudio that this is it's icon.

While Vivaldi is running execute the command `pactl list sink-inputs`. This will show how Vivaldi is setting it's audio stream properties.

**Comment by csehszlovakze** [comment]
You're right. I checked, and `application.icon_name` is `"chromium-browser"` while `application.process.binary` is `"vivaldi-bin"`. Closing the bug here and reporting it to them.
