### ISSUE TITLE
Auto gain sharp adjustment

### ISSUE THREAD

**Issue by parras** [wwmm/pulseeffects#550]
If I play back to back one loud then one quiet song, Auto gain behaves erratically. During the first 10-20 seconds of the quiet song, AG seems to be unresponsive to the lower sound level, except for the momentary loudness which drops immediately as expected. After a while, AG eventually becomes suddenly aware of the change in loudness: all values are updated at the same time, which results in a sharp increase in gain.

My understanding of the source code (https://github.com/wwmm/pulseeffects/blob/master/src/autogain/gstpeautogain.cpp#L358) is that, when the momentary loudness is lower than the relative threshold no gain correction is applied. I don't know if it's really the intended behaviour but in the use case I mentioned it results in a sharp, untimely rise of the sound level.

I'd be happy to file a PR if we can agree on an appropriate way to mitigate this issue.

**Comment by wwmm** [comment]
The current implementation has a few rough edges. My intention when comparing the momentary and the relative value was to avoid volume changes when a movie has moments of silence and the sound level before and after this silence stays the same. But as you noticed this has some side effects when the skipping tracks with very different volume levels because the relative value will not have time to change accordingly.

Honestly I am not sure if there is a way to handle both situations. I think that for movies the current behavior is ok. But it isn't when skipping tracks with very different levels. What do you have in mind? Maybe the best approach would be to have a switch or a toggle button in the interface with a name like `enable fast reaction` that would disable the comparison to the relative value. This way the user would be able to optimize the auto gain behavior.

**Comment by parras** [comment]
Yes, a single switch might be a good and simple solution. Another, more complex option would be to have AG behave like a very slow compressor (high attack and release times) as used in FM radio sound processing (http://www.radioautomation.com/soundprocessor.php). The user would then be able to choose both delay and predelay depending on the specific use case.
I'll try to experiment with those next week, when I get some free time.

**Comment by Digitalone1** [comment]
Hello parras, I tried AG for months but I didn't find it very good. It may be adjusted, but in the meantime I recommend you to use Maximizer as a volume normalizer. Just put release at maximum and play with threshold and ceiling values, it's the best plugin.

**Comment by parras** [comment]
Thanks @Digitalone1 for the hint. I actually already use Maximizer but at the end of the processing chain. I'll try to put it in first position and see if I can get what I want.

**Comment by wwmm** [comment]
Depending on what you want the maximizer will be more efficient. But have in mind it does not have perceived loudness as target. So this you can not replace with it. And unless you manually adjust each song level accordingly it will change the dynamic range a lot. Sometimes that is exactly what you want. That is why I use the maximizer on movies. But when listening to music it changes the dynamic range way more than I would like. 

The auto gain may or may not change song's dynamic range. When listening to classical music it will definitely change because this style has a very large dynamic range. But for other styles like pop or rock this change is minimal if the integrated signal has more weight than the momentary or the short term.

**Comment by parras** [comment]
After playing a bit, I found the following was adequate to my needs: AG without momentary-relative comparison and giving more weight to short-term and integrated loudness. On the other hand, Maximizer when placed first in the pipeline squashes the dynamics too much.
So I'll try to work out a patch to a switch in the UI as @wwmm suggested and file a PR shortly.

**Comment by Mlocik97-issues** [comment]
I have one idea... Have a big buffer, and calculate maximum, average and median of volume at full spectrum in buffer and compare it to values with previous values, calculate ratio and then combine it with relative loudness value, and this can be used to change volume on buffer. It will have only one side-effect, sound will be delayed little more.

**Comment by wwmm** [comment]
I don't think that the delay is the only side effect. If we use these averages to decide the gain we will lose the perceived loudness estimated by the ebur128 library. It is best to use the momentary, integrated and short term loudness values for that.

I will test again how things are when we do not compare the momentary and the relative value. Maybe I confused things and this comparison is not necessary in any situation. I implemented this a long time ago and now I can't remember exactly how bad was the problem that made me to do this comparison.

**Comment by parras** [comment]
In the past few days, I've been evaluating the impact of not comparing momentary against relative. As mentioned earlier, it appropriately fixes the sharp-and-delayed-adjustment problem. However, it has the nasty side effect of raising the volume of background noise when the SNR is poor, for instance with digitalised vinyls. It's easy to mitigate though by prepending the Gate module in the pipeline.

**Comment by Mlocik97-issues** [comment]
@wwmm Now I think about it, and I understand. Is there way how to use relative value only on half? Or use some limit, how volume can change over time (I know this limit can affect dynamics of audio)?

**Comment by wwmm** [comment]
Maybe that was it parras. If the auto gain is always active and there is a short moment of silence it will amplify noise.

@Mlocik97-issues this is something that could be considered. I am only afraid that in the end the user would have to touch this relative control knob as frequently we touch the volume control when there is no auto gain enabled. The ideal solution would be to find a way to handle this problem automatically.

It is not obvious at first sight but our reaction time can be indirectly controlled by a clever choice of weights. The more weight you give to the integrated loudness the slower our reaction will be. If the momentary has more weight than the other loudness values then we react very fast.

**Comment by Mlocik97-issues** [comment]
> The more weight you give to the integrated loudness the slower our reaction will be

yes, but it's time to react, not how fast it will change volume.

It's different when You want -10dB, but You have 5 seconds -20dB and then it will change to -10dB for 0.2 seconds. And it's different, when it start react imediately, but will change volume from -20dB to -10dB for 5 seconds (2dB for seconds). Now it's working like now You are playing quieter song, so I Auto Gain will wait 10 seconds, and after I will change really fast change volume to maximum... it's what is happening now. User even can hear how volume is changing. (I'm sure about it, because I tried both settings (Integrated 100, Momentary 1 and Integrated 1, Momentary 100) and it's anoying). It shouldn't change volume so fast over time, when input volume is not changing fast. It should change volume fast only if input volume will change from -30dB to -3dB for example. I know this is really complicated problem. And I don't know if there is way how to handle it. When there are so big changes in volume in short time (mainly when Momentary is under Target, as I know, and when you set giht Weight for Short Term, because Short Term is not affected over time by Momentary value when input is quieter). **When I'm listening to "Turkum - Beast" at start it's changing volume like kangaroo on steroids.**

**Comment by wwmm** [comment]
Is there a free sample of this material you are listening to somewhere? Here on my computer if I set the integrated weight to 100 this while listening to this song https://www.youtube.com/watch?v=q7VnD6Dqx4M the auto gain takes quit some time to make changes to its output gain. I think nothing I listen to makes the auto gain behave the way you are describing.

In any case as the integrated loudness "remembers" everything that went through PE in the current execution what you were listening to before is very relevant. This is probably contributing to such a big difference in experience. For me the auto gain has been mostly ok. When listening to music and movies I usually have it at
```
momentary = 1, short term = 2, integrated = 5
```
and when watching someone doing comments in a gameplay I use
```
momentary = 3, short term = 2, integrated = 1
```
I do no notice jumps or any other kind o annoyance. But as I said the overall experience probably changes with the audio material being used.

**Comment by wwmm** [comment]
Look ahead is another thing to consider. But it introduces more latency. And there is always the question about how much it is necessary to look ahead to solve this problem. When listening to music it is not a big deal. But when watching movies we do not want to completely destroy the sync between audio and video.

**Comment by wwmm** [comment]
I still think that there must be a way to combine the estimated loudness in a way that the resulting auto gain would be better. Although I am a physicist Audio signal processing is not my original field of expertise. So the most I could do was averaging these loudness and exposing the weights to the user. There has to be a better way out there. But I have no idea. I will try to research a little about other auto gains based on the ebur128 standard. Maybe there is something that could show us the right direction.

**Comment by wwmm** [comment]
But I agree that if the incoming signal has a ridiculously stronger signal only a look ahead can help.

**Comment by Mlocik97-issues** [comment]
Now I have these settings for music and movies:

```
"autogain": {
            "state": "true",
            "input-gain": "0",
            "output-gain": "20",
            "target": "-50",
            "weight-m": "60",
            "weight-s": "30",
            "weight-i": "80"
        }
```

**Comment by wwmm** [comment]
@Mlocik97-issues try to experiment a little with larger block sizes
![Screenshot from 2019-08-11 11-34-02](https://user-images.githubusercontent.com/16225172/62835218-0b8ec680-bc2c-11e9-9f6f-8da150761ca2.png)
It isn't the same as a look ahead but using 4096 instead of the default 512 the audio buffer processed will be larger and at each iteration the library ebur128 will have more info about the audio content. Maybe this helps to better estimate the loudness. Or maybe not... But even if nothing changes at least you will save a little of cpu power. This library use is more efficient when working with larger buffer sizes.  As usual the latency will increase.

I am taking a look at the code to see how hard it will be to implement a look ahead. It seems it is going to require more work than I though it would...

**Comment by wwmm** [comment]
I usually have my block size at 4096 when listening to music. Maybe this is the reason why I do not notice volume oscillations when skipping tracks.

**Comment by Mlocik97-issues** [comment]
block size at 4096 helped for auto-gain, but increased delay so much (from 121ms to 202ms, and it was bad for movies) and I had FPS drops in app.

**Comment by wwmm** [comment]
Larger blocks will increase latency. But this is not the only parameter that affects it. You probably have the buffer parameter in the same menu set to the default value of 200000 microseconds. Depending on the hardware you can use lower values like 50000 or 40000 microseconds without introducing noises. This should decrease the latency close to 150 milliseconds. At least in my experience bluetooth phones are the only devices that need high buffer values.

In any case large block values are not a real solution. Because of the large latency increase this is not something you want to do in some situations.

**Comment by wwmm** [comment]
I had time today to work on this
![Screenshot from 2019-09-05 15-41-00](https://user-images.githubusercontent.com/16225172/64369911-a7c1a880-cff3-11e9-8cca-eec63b43b2ee.png)
It is available on master branch.

**Comment by parras** [comment]
The combination of "Reset History" and "Detect Silence" perfectly solves the issue. Thanks a lot for implementing this!
