### ISSUE TITLE
Audio from Chrome 76 is crackling first minutes after play audio (if long time wasn't playing in this app).

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/pulseeffects#561]
I have this problem, I tried some advices, like 500000us buffer size, real-time priority and
`load-module module-udev-detect tsched=0` config

**Comment by wwmm** [comment]
Only AAC? I ask because PulseEffects process only raw audio(PCM). At the end of the day this is the format Pulseaudio has to send us. Compressed audio cannot be processed directly.

Are you using a bluetooth device? But even in this case a buffer value of 500000 us should be high enough to avoid cracklings. There are situations where the crackling is caused by problems in the driver or in Pulseaudio and the audio effects applied by PulseEffects are only making them easier to notice.

**Comment by Mlocik97-issues** [comment]
About AAC, after longer time, it seems it's cracling random, but only from Chrome app.
No I'm using 3.5 jack.

**Comment by Mlocik97-issues** [comment]
https://youtu.be/URDQ20TxlL0

(in video, these cracklings and effects are applied 2x).
Chrome -> Output
Output -> OBS

in pulseeffects I have output value of every plugin under -10dB, my presset:
https://gist.github.com/Mlocik97/34d87f5b6a368d4123075a3cb81d5e70

When I turn off equalizer, it's crackling much less. But I had same equalizer settings in Windows / Winamp, and it wasn't crackling. And these cracklings stop after while.

**Comment by Mlocik97-issues** [comment]
No, I have only PulseEffects and Pavucontroll for controlling audio.
OBS is program, I used to record that output (cracklings)

**Comment by Mlocik97-issues** [comment]
It seems it's on Chrome side. In beta version, it work OK.
