### ISSUE TITLE
Some effects of PulseEffects don't work

### ISSUE THREAD

**Issue by jotape1960** [wwmm/pulseeffects#583]
I use PulseEffects 4.6.8 with Ubuntu Studio 19.04, upgraded from 18.04.3. It is a 64 bits installation.

Since the upgrading, some of the internal PulseEffects effects cannot to be used, they don't work.

The only useful effects are: Auto Gain, Maximizer, Convolver, Crystalizer, Crossfeed and Pitch.

All the other effects don't work at all!!!

What's wrong, here?

How can I fix this?

**Comment by wwmm** [comment]
Try to remove GStreamer's cache `rm -rf ~/.cache/gstreamer-1.0`. If that does not work check if some of the other plugins were removed by the upgrade.

**Comment by pjackowski** [comment]
I am trying to debug a similar issue in Fedora 29. I see "no plugin found" errors most of the time and effects aren't available. However, I noticed a few occasions when plugins loaded and effects were clickable. For instance, I have tested equalizer on output, but now it is inactive.

Some effects don't seem to work on input, as I could not tell the difference in recorded samples in Audacity. This might be caused by plugins being incorrectly detected. I will keep testing and try to identify pattern.

Packages I have installed from dependencies:

Installing:
 pulseeffects
Installing dependencies:
 libebur128
 lsp-plugins-lv2
 lv2
 calf
 fluidsynth-libs
 game-music-emu
 gstreamer1-plugins-bad-free-extras
 ladspa-calf-plugins
 lash-libs
 libchromaprint
 libkate
 libofa
 lv2-calf-plugins
 lv2-mdala-plugins
 zita-convolver
Installing weak dependencies:
 rubberband
 ladspa-zam-plugins
 lv2-zam-plugins
 zam-plugins

**Comment by wwmm** [comment]
I do not remember a case where this was random. Usually these are the reasons for a `not found plugin`:
```
- The plugin is not installed or has the wrong API(ladspa instead of LV2 for exemple)
- GStreamer cache is corrupted. In this case deleting it solves the problem.
- The lilv library is not installed
- GStreamer plugins bad was not compiled with lilv support
```

There were a few bizarre issues in the past where PE had a segmentation fault because the user system had a critical package like Pulseaudio upgraded and no reboot was made. But I do not remember this being necessary to find plugins.

**Comment by pjackowski** [comment]
Hey, thanks for a very quick reply. I have just found issue #513, which documents this behaviour. Apparently resetting settings make all plugins "active", because pulseeffects checks for plugins on startup only ;-)

https://github.com/wwmm/pulseeffects/issues/513

**Comment by wwmm** [comment]
I wonder why you have `ladspa-calf-plugins` and `libkate` as dependency. Here on Arch Linux I do not have libkate installed. And we use the LV2 implementation of Calf Plugins. the package `calf` is enough.

**Comment by wwmm** [comment]
Yes. The reset has this weird side effect.

**Comment by pjackowski** [comment]
Thank you for advice. I will keep looking into it. Pulseeffects is such a great project, it would be a shame if it suffered because of incorrect dependencies. Maybe maintainer was confused and unsure which plugins API is required and tossed in ladspa just in case ;-)

I have already cleared GStreamer cache, but will look into lilv library and GStreamer compilation flags.

**Comment by pjackowski** [comment]
I have checked new Fedora 31 release published earlier this week and issue with missing effects is almost fixed. There is only one output effect missing, which is great because in Fedora 29 as many as 23 effects are missing. Errors during startup are as follows, but I consider it resolved.

```
[liveuser@localhost-live ~]$ pulseeffects 
(pulseeffects:33168): pulseeffects-WARNING **: 23:54:32.322: loudness plugin was not found!
```

**Comment by wwmm** [comment]
The loudness plugin is from this library https://drobilla.net/software/mda-lv2. Based on one of your comments above this should be provided by the package `lv2-mdala-plugins`

**Comment by pjackowski** [comment]
Thanks for confirming package name.

I figured out this is an issue with missing package `lv2-mdala-plugins` that had been retired in F31 and is no longer available. This might have something to do with Fedora dropping 32-bit OS images and reduced support for 32-bit packages moving forward. I have seen bug report stating package had failed to build in F31 tests. I will see if this is something I can fix.

Fun fact, `lv2-mdala-plugins` was installed in F29, nonetheless, loudness plugin had failed to load in F29! This reminds me The X-Files ;)

**Comment by wwmm** [comment]
In case it helps this is how Arch Linux maintainers are compiling this library on x86_64 https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mda.lv2
