### ISSUE TITLE
Ubuntu 19.10's PulseAudio package is out of date

### ISSUE THREAD

**Issue by mmstick** [wwmm/pulseeffects#585]

**Comment by mikhailnov** [comment]
It is not out of date. https://launchpad.net/~mikhailnov/+archive/ubuntu/pulseeffects/+packages
It is even with current git master.

**Comment by mmstick** [comment]
See the "(newer version available)" link. The new Ubuntu release is on version 13.0, whereas the PPA is still providing 12.2 for it.

**Comment by wwmm** [comment]
If he is building from Pulseaudio's master branch  the problem is only the name. The code itself is updated.

**Comment by mikhailnov** [comment]
> See the "(newer version available)" link. The new Ubuntu release is on version 13.0, whereas the PPA is still providing 12.2 for it.

Sorry, I thought you wrote about PulseEffectes, not PulseAudio.

Yes, I once built PulseAudio 12.2 with backported `norewinds` (https://gitlab.com/nixtux-packaging/pulseaudio-ubuntu/blob/master/pulseaudio-12.2/debian/patches/0001-Backport-add-an-option-that-allows-rewinds-to-be-dis.patch) which was needed for PulseEffects for all Ubuntu releases.

Now PulseAudio 13.0 is in the official repo of Ubuntu 19.10, and so PulseaDuio from the PPA will not be installed because the package in another repository is newer.

I don't plan to build PulseAudio for Ubuntu 19.10 as there is no sense for it. `norewinds` option is already in PulseAudio 13.0.

**Comment by mikhailnov** [comment]
You are probably asking about this because you copied PulseAudio packages from pulseeffects ppa to PopOS ppa (https://launchpad.net/~system76/+archive/ubuntu/pop/+packages?field.name_filter=pulse&field.status_filter=published&field.series_filter=) and now users of PopOS based on Ubuntu 19.10 can't update PulseAudio.

I once already suggested you to remove priority 1001 of your PPA in PopOS. I don't know ho to deal with the current situation if you already have users on 19.10. Maybe try removing pulseaudio package from the ppa. I don't know how apt will deal with it.

**Comment by mikhailnov** [comment]
Or meybe add an exception for `libpulse*` and `pulseaudio*` packages to the apt config that sets Priority=1001

**Comment by mikhailnov** [comment]
I've asked people who use PopOS 19.10 to show `dpkgs -s pulseaudio`. My package of pulseaudio is really preinstalled. All applications in Ubuntu repository and in your PPA are linked against `libpulse.so` 13.0, but you ship 12.2 in your distro.
Have a look at https://abi-laboratory.pro/index.php?view=timeline&l=pulseaudio
See 6 new symbols in 13.0 compared to 12.2?
Some applications make crash due to missing symbols in libpulse.
