### ISSUE TITLE
Importing generic EQ presets

### ISSUE THREAD

**Issue by Shurichan** [wwmm/pulseeffects#588]
[left4.txt](https://github.com/wwmm/pulseeffects/files/3813097/left4.txt)
I believe that this generic format originated from Eq APO? Turns out that importing these to PA manually every time is a massive pain!
I looked into using a script to insert the EQ data to the PA json files, but parsing the files seems to be beyond me.
PA already appears to aim for comparability with APO, so this would be a great add IMO.

**Comment by polygonalenippel** [comment]
I second this.

An often used tool is AutoEQ: https://github.com/jaakkopasanen/AutoEq/
It outputs several formats, one of which is a parametric EQ which is very similar to what you posted:
```
Filter 1: ON PK Fc 52 Hz Gain -6.6 dB Q 0.97
Filter 2: ON PK Fc 139 Hz Gain -1.8 dB Q 3.07
Filter 3: ON PK Fc 171 Hz Gain -0.4 dB Q 2.41
Filter 4: ON PK Fc 210 Hz Gain 4.8 dB Q 2.00
Filter 5: ON PK Fc 522 Hz Gain 0.5 dB Q 2.47
Filter 6: ON PK Fc 2066 Hz Gain -0.9 dB Q 0.71
Filter 7: ON PK Fc 2432 Hz Gain -3.3 dB Q 2.40
Filter 8: ON PK Fc 3665 Hz Gain 9.0 dB Q 2.17
Filter 9: ON PK Fc 6467 Hz Gain -5.2 dB Q 1.48
Filter 10: ON PK Fc 19607 Hz Gain -7.1 dB Q 0.32
```
Right now there is no way of importing this. You could use a simple perl script or `jq` and `awk` perhaps to parse it into a PE config json, but yeah.

I suggest adding a button in the Equalizer screen to import such file and parse it into the current preset.

Some useful links:
AutoEQ implementation: https://github.com/jaakkopasanen/AutoEq/blob/aa25ed8e8270c523893fadbda57e9811c65733f1/frequency_response.py#L675
APO config reference: https://sourceforge.net/p/equalizerapo/wiki/Configuration%20reference/

Note: the preamp is basically the Input slider of the equalizer

Also, maybe it's a good begin to support just PK Fc filters since that's what AutoEQ does as well: https://github.com/jaakkopasanen/AutoEq/issues/102

**Comment by Shurichan** [comment]
The newest standalone version of the used LSP Parametric Equalizer plugin does have support for importing a REW file.
![Screenshot_20200802_131251](https://user-images.githubusercontent.com/13228415/89120845-189e6880-d4c2-11ea-9a81-958466692f51.png)

**Comment by wwmm** [comment]
GStreamer's support to LV2 plugins isn't complete. Parameters involved in file importing can not be used. This feature will have to be written from scratch in PulseEffects.

**Comment by polygonalenippel** [comment]
I will try to write one, but considering I've never used Boost or GTK before don't hold your breath.

**Comment by polygonalenippel** [comment]
@wwmm I tried looking at it but I really don't feel like delving into GTK, could you help me out? I tried duplicating some code from the convolver screen and ended up with something that almost worked. Here's a great starting point.

```cpp
struct FilterSettings {
    float freq;
    float gain;
    float quality_factor;
};

bool parse_eq_filter_file_line(std::string& line, struct FilterSettings& filter) {
  std::string::size_type n;

  // don't panic!
  std::regex re(R"(Filter[\s]*[\d]*:[\s]*ON[\s]*PK[\s]*Fc[\s]*([0-9]*[.]?[0-9]+)[\s]*Hz[\s]*Gain[\s]*([+-]?[0-9]*[.]?[0-9]+)[\s]*dB[\s]*Q[\s]*([0-9]*[.]?[0-9]+))");
  std::smatch matches;

  if (std::regex_search(line, matches, re)) {
    if (matches.size() != 4) {
      return false;
    }

    filter.freq = std::stof(matches.str(1));
    filter.gain = std::stof(matches.str(2));
    filter.quality_factor = std::stof(matches.str(3));

    return true;
  }

  return false;
}

void EqualizerUi::import_parametric_eq_file(const std::string& file_path) {
  boost::filesystem::path p{file_path};

  std::ifstream eq_file;
  eq_file.open(p.string());
  std::string line;
  std::vector<struct FilterSettings> filters;

  if (eq_file.is_open()) {
    while (getline(eq_file, line)) {
      struct FilterSettings filter;

      if (parse_eq_filter_file_line(line, filter)) {
        filters.push_back(filter);
      }
    }
  }

  for (struct FilterSettings f : filters) {
    // add bands here
  }

  eq_file.close();
}
```

**Comment by wwmm** [comment]
>// don't panic!
  std::regex re(R"(Filter[\s]*[\d]*:[\s]*ON[\s]*PK[\s]*Fc[\s]*([0-9]*[.]?[0-9]+)[\s]*Hz[\s]*Gain[\s]*([+-]?[0-9]*[.]?[0-9]+)[\s]*dB[\s]*Q[\s]*([0-9]*[.]?[0-9]+))");

Too late! What the hell is this doing? :D

>I really don't feel like delving into GTK

I will take care of the GTK bits.

**Comment by wwmm** [comment]
Do APO presets use an specific file extension? Or does it reads any text file without caring about the extension? I ask because it would be nice to have only one import button and change algorithms based on the file extension in case we have to support other formats in the future. For now I will just call the button `Import APO Presets`

**Comment by polygonalenippel** [comment]
> Too late! What the hell is this doing? :D

The best regexes are concocted at 3:00 in the morning.
Each line in the file is thrown into `parse_eq_filter_file_line()`, which executes the regex on said line. The results are stored in the variable `matches`. Assume for now the line passes the regex, meaning it is a filter line which we seek.

Each line is checked to satisfy something along the lines of:
`Filter 2: ON PK Fc 139 Hz Gain -1.8 dB Q 3.07`
I made the regex extra meaty to allow for variable whitespace, so as long as those keywords (case sensitive) accompanied by their respective values are in there, it should work.

Furthermore, the regex contains several so called 'capture groups', which operate on the values we seek (`freq`, `gain`, `quality_factor`). This means that our `matches` gets to look like this:

1. the full line (because if the regex matches, that itself is a match)
2. the freq
3. the gain
4. the quality factor.

Note this is very strict, all capture groups have to be present or the entirety of the match fails and the line is skipped.

If this is not clear enough I can go into more detail.

> Do APO presets use an specific file extension?

As far as I know it's a `.txt`, but correct me if I'm wrong.

**Comment by polygonalenippel** [comment]
For fun, you can throw it into https://regex101.com/ to play with it if you like and see if you can break it.

**Comment by wwmm** [comment]
Master branch has been updated with initial support to APO preset importing. But it has to be improved. Right now all the bands are set to `Bell`. It is the same as the `Peak` type in the APO examples above. They are those `PK` in each lines. At this moment these are the values supported by the parameter `type` in the equalizer plugin used in PulseEffects:
```
Off
Bell
Hi-pass
Hi-shelf
Lo-pass
Lo-shelf
Notch
Resonance
```

As I said above `Bell` corresponding to `Peak` in most equalizers. `Hi-pass` is our high pass filter and `Hi-shelf` is the high shelf filter. Same logic applies to the `Lo-`. We have to know what APO does when saving these kind of filters to the preset file so we can map each value accordingly.

@polygonalenippel I have no idea about how to adjust that regex to catch this information :D XD

**Comment by polygonalenippel** [comment]
I don't use Windows so unfortunately I cannot mess around with APO.

Judging by the doc which I linked, specifically this part: https://sourceforge.net/p/equalizerapo/wiki/Configuration%20reference/#filter it seems that certain filter types have different parameter requirements (e.g. LS needs no Q-factor). This again can be done with regex, but I will take other methods to solve this into consideration as well.
You see, you can fix it with a fancy parser but it gets long and complex down the road usually (in C++).

I have some time to look at it tonight, that is, in a few hours. @wwmm If you have already begun working in a branch, please link it here so I have more context to work with.

**Comment by wwmm** [comment]
>If you have already begun working in a branch, please link it here so I have more context to work with

Everything I did is already in the master branch https://github.com/wwmm/pulseeffects/blob/403269c3c2d61c1e56c98657ba8d86e3952ded30/src/equalizer_ui.cpp#L832

**Comment by polygonalenippel** [comment]
The more I look into the APO specs, the more of a headache I get. It's pretty inconsistent...

You could change them up top a little:

```cpp
// you can use descriptive names with maps, but I believe C++ will resolve them to
//   an int at some point so it's useless
enum FilterType {
  "PK",
  "LP",
  "LPQ",
  "HP",
  "HPQ",
  "BP",
  "LSC",
  "HS",
  "HSC",
  "NO",
  "AP",
};

struct ImportedBand {
  enum FilterType type;
  float freq;
  float gain;
  float quality_factor;
  float dB_per_octave;
};
```

So you have a little more freedom when parsing:

```cpp
// returns false if line could not be parsed successfully
bool parse_apo_filter(const std::string& line, struct EqualizerUi::ImportedBand& filter) {
  
  std::regex re_filter_type(R"(Filter[\s]*[\d]+:[\s]+ON[\s]+([\w]*))");
  std::regex re_freq(R"(Fc[\s]+([0-9]*[.]?[0-9]+)[\s]*Hz)");
  std::regex re_gain(R"(Gain[\s]+([+-]?[0-9]*[.]?[0-9]+)[\s]*dB)");
  std::regex re_quality_factor(R"(Q[\s]+([0-9]*[.]?[0-9]+))");
  std::regex re_dB_per_octave(R"(Filter[\s]*[\d]+:[\s]+ON[\s]+[\w]*[\s]*([\d]+)[\s]?dB)");
  std::smatch matches;
  
  std::regex_search(line, matches, re_filter_type);
  if (matches.size() != 2) {
    return false;
  }
  filter.type = matches.str(1);
  
  std::regex_search(line, matches, re_freq);
  if (matches.size() != 2) {
    return false;
  }
  filter.freq = std::stof(matches.str(1));
  
  // if filter type in {PK, LPQ, HPQ, BP, ...?}
  //   get the quality_factor

  // if filter type in {LSC, HSC, LS, HS}
  //   get the dB_per_octave
  
  return true;
}

void EqualizerUi::import_apo_preset(const std::string& file_path) {
  boost::filesystem::path p{file_path};

  if (boost::filesystem::is_regular_file(p)) {
    std::ifstream eq_file;
    std::vector<struct EqualizerUi::ImportedBand> bands;

    eq_file.open(p.string());

    if (eq_file.is_open()) {
      std::string line;

      while (getline(eq_file, line)) {
        struct EqualizerUi::ImportedBand filter {};
        bool parsed = false;
        
        try {
          parsed = parse_apo_filter(line, filter)
        } catch (...) {
          continue;
        }
        
        if (parsed) {
          bands.push_back(filter);
        }
      }
    }

    eq_file.close();

  // ...
```

I still can't wrap my head around some things:

* Modal and PEQ I don't understand
* In the HSC example in the APO specs, they included a space in between the 6 and the dB. I accounted for it in the regex
* Some filter types have a Q suffix (e.g. LP has LPQ). Those obviously have a Q parameter, but some lack the extra suffix type yet they have a Q. E.g.: `ON BP Fc 1000 Hz Q 0.100` even though BPQ does not exist. This means some parameter criteria are truly optional, others are optional in the sense that they have the Q suffix.

I haven't tested the code because I'm really tired and have a few other things to do, so see if it's any good.

The pre-amp also needs to be added though that's trivial.

**Comment by polygonalenippel** [comment]
I've continued working on the parser. The sooner I deal with this, the more curses I get to spare because boy this format sure is batshit.

**Comment by polygonalenippel** [comment]
Things which still need to be addressed:

1. Peaking filters' `target` and `Oct`.
  What am I supposed to do with this?
2. Channels.
  I don't feel like doing this.
3. Microphone filters
  Looks doable
4. Preamp
  Also not that difficult
5. Maybe GraphicEQ?
  If there's any interest in this I could take a look into it
6. Weird float parsing behavior
  I think C++ looks at the current locale when it tries to parse floats. In some Euro countries, we use the comma `,` to denote decimals (e.g. 5,45 instead of American 5.45). So if you're in commaville, the dotty values are still parsed but neglecting the decimals. So 5,45 becomes 5.00 I think, not sure.

@wwmm What's your opinion on these points and the PR as it stands so far?

**Comment by wwmm** [comment]
> What's the purpose of putting ON in each filter setting if no OFF exists?

I never used APO so I have no idea.

>Why is the Q of the band pass filter optional???

Strange. I imagine that some kind of popular default value must be used when no quality factor is given. In any case the equalizer used in PulseEffects has no band-pass. A separate plugin has to be used for that.

>Peaking filters' target and Oct

I don't know. But considering that the `target` parameter unit is `ms` I doubt it is a parameter we can use in our equalizer. The same goes to the `Oct`. They say `Oct <Bandwidth value>` but it is not clear what they mean by that.

> Channels

At this moment PulseEffects is a stereo application. And changing that is hard. So we will have to ignore the number of channels in these presets.

**Comment by wwmm** [comment]
I have been a little busy but I will take a look at the PR as soon as possible

**Comment by wwmm** [comment]
PE `4.8.0` release with partial APO preset importing support. I doubt we will ever be 100 % compatible. For example PulseEffects is a stereo application and does not support surround. But the current support should be enough for the simple APO preset files.
