### ISSUE TITLE
sample format and rate

### ISSUE THREAD

**Issue by ear9mrn** [wwmm/pulseeffects#609]
Two questions rather than issues.

currently I have the following sample rate, sample format chain.

float32le,96.0kHz->F32LE,96.0kHz->s32le,96.0kHz.

![pulse](https://user-images.githubusercontent.com/471260/72205180-056d7200-3478-11ea-99c6-5ee540b6693b.png)

1) In this scenario am I correct in assuming there is no re-sampling taking place as the sampling is the same at each step?
2) is it possible to change the output sample format method from s32le? I have looked around the GUI and source and cannot see anything obvious.

Thanks,

Pete.

**Comment by wwmm** [comment]
Yes. There is no resampling taking place. This the optimal case.

You can change the sample format but this has to be done in this Pulseaudio file `/etc/pulse/daemon.conf`. In case you do not want to edit a system file copy `daemon.conf` to the folder `~/.confg.pulse` and edit the field `default-sample-format` accordingly. Remember to uncomment it by removing the `;` character in the beginning of the line.

It has to be this way because this last info showed in PE title bar are the properties of the output device. They can only be changed in the `daemon.conf` file.

If you are worried about the fact that the output device is using `s32le` instead of `float32le`(the same as `F32LE`) don't be. There won't be any quality loss in this case. And I never saw a sound card with native support for `float32le`. The only situation the sample format conversion could become a problem is if have an audio content recorded with 32 bits and forces it to be played at 16 bits. Moving from float to integer keeping the bit depth does no harm.

**Comment by wwmm** [comment]
You may try to set `default-sample-format` to `float32le` and run `pactl list sinks` to see if it worked. At least my sound card does not support it. Pulseaudio is forced to fallback to `s32le`.

**Comment by ear9mrn** [comment]
many thanks. So in the case shown above I already have `default-sample-format = float32le` set in daemon.conf. 
The middle sample format is that what pulseeffects uses and is this hardwired? `F32LE`
Thanks for confirming that the last sample format is the actual sound card.
I did as you suggested `pactl list sinks` . My card shows `Sample Specification: s32le 2ch 96000Hz`. 

Thanks again. I understand this a lot more now, essentially keep the sampling the same!

Pete.

**Comment by wwmm** [comment]
The information in the middle is from the plugins processing chain. Almost all of them work only with the `F32LE` format and 2 channels. So this sample conversion is unavoidable. Plugins do that because doing the processing in float has advantages. If I am not mistaken among other things this removes the danger of number overflow when adding numbers in the processing. Fortunately this sample conversion causes no quality loss. If the content has only 16 bits the other 16 bits it does not have will be filled with harmless zeros.
