### ISSUE TITLE
Regression causes sound effect distortions

### ISSUE THREAD

**Issue by AsavarTzeth** [wwmm/pulseeffects#63]
Commit 9d8239545fa0f4cda4cc9fc3ef4d3a23dbe07682 and possibly ones that follow causes regressions in some of PulseEffects sound effects. Not sure which plugin, but something causes static in the sound. The music I play is still audible but the static is louder.

**Comment by wwmm** [comment]
Hmmm... This is strange. I did lots of tests with the new pipeline and everything is fine here. No static.

**Comment by wwmm** [comment]
In any case all the latest changes are being made to support a feature that are always asking me for. Supportting turning effects on and off. In other to be able to support this I had to lots of refactoring. Gstreamer pipeline included. Now each plugin is inside a GstInsertbin. Here I have no problems with this approach but maybe in other machines this is not true...

**Comment by AsavarTzeth** [comment]
Well I will wait and see then. Perhaps you can continue with your refactoring and give me a call when you feel you have reached a milestone. I would happily help with testing prior to a release.

**Comment by wwmm** [comment]
Hi! Do you still have this problem with the latest code in master? As I am considering making a new release  it would be good to know if this is still happening

**Comment by AsavarTzeth** [comment]
I will test it when later when I am done studying for the day. Looking forward to test it.

**Comment by AsavarTzeth** [comment]
Well my testing had to be delayed until the next day. Almost everything seem to work perfectly. You even seem to have fixed those annoying gtk resizing errors.

I think part of the reason why I had distortions were my own incompetence. I strongly suspect that my speakers simply are not powerful enough and I put things like output on too high levels. I say partly because on a rare occasion I still had issues, with default settings, but that seem to be resolved now.

There was one issue I detected at the end though. If I change latency-time to any other value everything is paused, including sound spectrum analyzer and all.

Output you should get when this happens:

```
** (pulseeffects:3): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
13:17:20.141 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)')
```

**Comment by wwmm** [comment]
I also have this error. Both with version 2.3.5 and the latest git. Something interesting is that if we restart pulseeffects using one of the latency values that triggered this error everything is fine. It seems that the problem is not the value itself but the fact it was set on the fly. Strange... I will take a deeper look into this.

**Comment by wwmm** [comment]
I did some tests and the problem happens when setting the latency of the microphone pipeline. I am setting the same value for both pipelines but clearly values that are ok in the app pipeline crash the microphone pipeline.

Honestly I think I will leave the mic pipeline with its default latency of 10 ms and let the user configure only the latency of the applications pipeline.
