### ISSUE TITLE
Graphic equalizer

### ISSUE THREAD

**Issue by bringmemyaxe** [wwmm/pulseeffects#634]
Is there a way to enable or create any graphic equalizer? Not a parametric one. Like in Equalizer APO. Parametric equalizers are hard to use, because if someone wants to make an accurate preset why would he choose parametric if graphic ones are exact? If I set -20 dB on 3500 Hz and -19 dB on 4000 Hz it is going to be -20 dB and -19 dB! Not -39 dB! That's a nonsense. How am I going to calculate every band's affections on others? Calculating them in a calculator? I'm really sorry, but it always is disappointing when there are really really good features but there's NO such a simple feature as a simple graphic equalizer.

**Comment by wwmm** [comment]
The default configuration works like a 30 bands graphic equalizer. And in case you do not want a graphic equalizer with 30 bands you can choose a smaller number of bands and click on the `calculate frequencies` button so that the center frequencies and bandwidths of a graphic equalizer with the chosen number of bands are calculated.
![Screenshot from 2020-02-27 11-12-38](https://user-images.githubusercontent.com/16225172/75453081-1acc2c00-5952-11ea-8236-722a1cea73a5.png)
There is absolutely nothing stopping you from using it like a graphic equalizer if that is what you want.

**Comment by wwmm** [comment]
There are even 10 bands presets that are a copy and paste of GStreamer's 10 bands graphic equalizer presets

**Comment by bringmemyaxe** [comment]
The presents from GStreamer were made for a graphic EQ, as I suppose. But each band and the EQ itself works as a parametric. 
![image](https://user-images.githubusercontent.com/48741931/75454156-e8e9b280-59af-11ea-9f91-828a51fdd83f.png) 
It is also mentioned in the manuals: 
![image](https://user-images.githubusercontent.com/48741931/75454241-1171ac80-59b0-11ea-8717-47ca97b5fdb7.png)

**Comment by bringmemyaxe** [comment]
The width parameter makes it impossible to make anything like this
![image](https://user-images.githubusercontent.com/48741931/75454744-e045ac00-59b0-11ea-8b42-951a40048061.png)
Though in graphic EQs it is possible without any widths.

**Comment by bringmemyaxe** [comment]
Unfortunately, the default configuration does not work like a 30 bands graphic equalizer. If you do it like this, you won't get 0 dB, you will get clipping. 
imgur.com/249fb98c-d92a-4ad6-adba-a1fb3ba58a89
It is the way parametric EQs work

**Comment by wwmm** [comment]
Which graphical equalizer have you used before that behaves like this? Not every graphical equalizer you will find out there is base on a combination of low and high shelf filters. If you take a look at GStreamer sources you will see that its graphic equalizer is just its parametric equalizer with center frequencies and bandwidths chosen to make it work like a graphic equalizer. They just hide the width parameter from the user. 

Our parametric equalizer is from Linux Plugins Studio https://lsp-plug.in/?page=manuals and its author has graphical equalizer variants. And accordingly to what he told last year they are based on low and high shelves. But if I am not mistaken the number of bands is fixed. Either I choose the one with 16 bands or the one with 32 bands.

The problem with this approach is that it won't take long for people starting to come here asking for other number of bands. They did this before when I used GStreamer equalizer. This is a one man job done for free on my free time. And I do not have the knowledge to make equalizers. So I can't make everyone happy :-). The parametric equalizer was the least effort solution.

That being said I can consider adding one of lsp graphical equalizers. Not all of them.

**Comment by bringmemyaxe** [comment]
For example, this is why I think parametric EQs are not convenient. On the first picture we do preamp -30 dB and set each band +15 dB which should result giving -15 dB. But in fact it works differently
![image](https://user-images.githubusercontent.com/48741931/75455961-e3429b80-59b4-11ea-83ab-fc8f4a7c38a0.png)
![image](https://user-images.githubusercontent.com/48741931/75455972-e76eb900-59b4-11ea-9151-d4aa84c9ff39.png)

**Comment by wwmm** [comment]
It would be helpful you repeated the test above in Ardour with this LSP plugin https://lsp-plug.in/?page=manuals&section=graph_equalizer_x32_lr. Given the large number of parameters the amount of work to integrate it in PulseEffects will be big. So it would be good to know that it actually fixes the problem before starting this journey.

**Comment by wwmm** [comment]
At least with the parametric equalizer I was able to support different number of bands by muting each band. With luck the same approach can be used with the graphical equalizer.

**Comment by bringmemyaxe** [comment]
Yeah, I get it, it is indeed a good solution for this approach. Thank you, I'll try testing LSP plugins and will search for a better solution if it doesn't work the right way.

**Comment by bringmemyaxe** [comment]
Oh, you are right... LSP's "graphic" equalizer is a mess, but definitely not graphic. Why were Windows's solutions easier :(

**Comment by wwmm** [comment]
Mess?

**Comment by wwmm** [comment]
These plugins are meant to be used by professionals and not the average user. Those guys need something powerful and flexible. If by mess you mean complexity and lots of parameters yeah... It is a "mess"...

Which are those easier windows solutions?

**Comment by bringmemyaxe** [comment]
I do agree these plugins are for professionals...

By saying easier windows solutions I meant Equalizer APO or ViPER4Windows. Even if I hadn't these two programs, I could use at least the standard equalizer in players such as AIMP or foobar2000 or any other player with graphic equalizer. They behave in a pretty simple way. As for me, the only "best" solution is to open Adobe Audition and change all audiofiles with the FFT filter which behaves as an extremely flexible graphic EQ with as many bands as you like from -300 dB to +15 dB... LOL... :D

**Comment by wwmm** [comment]
In any case the equalizer just has behave as intended. Most of those controls won't be visible once it is integrated in PulseEffects. The user will be able just to set the gains, select the number of bands(assuming that the mute approach is mathematically correct), and apply different settings for each channel(the split channel feature currently available in the parametric eq).

**Comment by bringmemyaxe** [comment]
Okay, thank you so much for the answers, as a matter of fact the EQ in PulseEffects works fine, sorry for bothering :)

**Comment by wwmm** [comment]
No problems :-). Something that Linux Studio Plugins author also told me last year is that it should be possible to make the parametric equalizer behave like a graphic by using a low shelf in the first band and high shelf on the others. This is what his graphic equalizer does under the hoods. What I don't know is how you would choose the frequency of each of these shelf filters to achieve this goal.

**Comment by alexhorner** [comment]
Hey @wwmm and @bringmemyaxe,

I have spoken to the LSP author myself today via email and he provided me with a configuration for the Parametric Equalizer which replicates his Graphic Equalizer x16 plugin.

It basically consists of a low shelf on the first band, ladder pass on between bands and a high shelf on the last band, plus a bunch of decimal width values, decimal frequency values and a Q of 0 on everything.

EasyEffects does not allow me to input decimal frequency values nor does it allow me to input 3 decimal places of precision for the width value, which is what his config calls for. As such, I have rounded to the closest precision possible (whole numbers for frequency and 2 decimal places for width) and it sounds pretty indistinguishably close.

The complexity of this however is not lost on me, and I am not happy with the fact all of this needed to be put in, inaccurately, to achieve the desired effect.

Is it possible to get this issue re-opened with the ultimate goal of adding the Graphic Equalizer x16 and maybe also x32 plugins to EasyEffects? I intend to take a look myself but not being a C++ dev I don't know if it'd be in my reach to achieve myself, we'll see.

**Comment by wwmm** [comment]
>EasyEffects does not allow me to input decimal frequency values nor does it allow me to input 3 decimal places of precision for the width value, which is what his config calls for. 

In this case I think we should make it possible to set the extra decimal places. Adding graphical equalizers locked to a given number of bands is something I would like to avoid because it is not going to take long for people to start asking for equalizers with other number of bands. This route will increase the maintenance burden too much on my opinion.

Something we could consider is adding a "graphical equalizer" button take tries to automate the process LSP author describes to mimic the graphical equalizer with the parametric eq. But it would probably be better to do that in the Qt branch after the equalizer is ported to it.

**Comment by wwmm** [comment]
>Something we could consider is adding a "graphical equalizer" button

I mean as an operation mode in the current equalizer window and not as a new plugin in the plugin list.

**Comment by alexhorner** [comment]
> > Something we could consider is adding a "graphical equalizer" button
> 
> I mean as an operation mode in the current equalizer window and not as a new plugin in the plugin list.

I think it would be nice to support both the x16 and x32 channel variants already provided by LSP, because the same argument could be made for the existing Parametric EQ which cannot go above 32 even if people ask for it.

**Comment by wwmm** [comment]
>I think it would be nice to support both the x16 and x32 channel variants already provided by LSP, because the same argument could be made for the existing Parametric EQ which cannot go above 32 even if people ask for it.

I do not disagree it would be nice. It would definitely be convenient for some users. As plenty of other things that have been requested and so far not implemented would also be. But at the end of the day we have to be realistic and take into account how many people have actually regularly taken part in code maintenance along the years. With the exception of the collaborators involved with package maintenance it is mostly me and one more person. Supporting an equalizer (or any other plugin in a similar situation) for each variant provided by LSP isn't the way to go. The only reason why we have more than one "noise reduction" filter is because it is not uncommon to be in a situation where one noise reduction algorithm becomes completely useless. In the equalizer it is a different situation. With the exception of the corner cases where it really has to be a graphical equalizer or more bands than the parametric equalizer provides are needed it is a matter of how hard or annoying it is to setup and not if it is impossible to get close to the target or not. If it is possible to do with the current parametric equalizer but annoying to setup what we have to do is making it less annoying.
