### ISSUE TITLE
Registers Useless Clients

### ISSUE THREAD

**Issue by ChiragKalra** [wwmm/pulseeffects#635]
Useless PulseEffects sliders show up in output volume widget in raven applet.
![ss](https://user-images.githubusercontent.com/24735099/75567783-18fc8880-5a78-11ea-845f-501ce8d68fc7.png)

I'm using Ubuntu-Budgie 19.10.

**Comment by wwmm** [comment]
Unfortunately this cannot be fixed in PulseEffects. Raven applet developers will have to add some kind of blacklist. The reason is that those virtual devices and recording streams have to be created. And when Pulseaudio does that it adds those volume controls. It is up to the volume manager software to decide which controls it shows or does not show. There is no flag in Pulseaudio I could set to make those controls invisible in third party apps.

By the way I also had to add a built-in blacklist in PulseEffects for streams that do not make sense to be shown to our users. Unfortunately each app that interacts with Pulseaudio has to do that on its own.

**Comment by ChiragKalra** [comment]
I contacted the developer of Raven applet and they suggest adding flags telling the API users these streams are virtual and must be hidden away from the user.

**Comment by wwmm** [comment]
I am curious about how he thinks this can be done. Pulseaudio has no virtual flag for streams https://freedesktop.org/software/pulseaudio/doxygen/def_8h.html#a6966d809483170bc6d2e6c16188850fc. And if it had one The stream is created inside of GStreamer. And Gstreamer does not allow Pulseaudio flags to be set. They do that internally.

Maybe what he is really thinking about is setting custom properties in our streams so that he can filter them. This is already there. All he has to do is reading the `application.id` when asking Pulseaudio for streams properties. Anything is starting with `com.github.wwmm.pulseeffects` is ours and should be hidden from the users.

**Comment by wwmm** [comment]
Or could it be that he thinks I am one of Pulseaudio developers? I am not XD. As much as I would like adding more flags to Pulseaudio API is beyond my reach :-)

**Comment by wwmm** [comment]
Closing as fixing this is out of my reach.
