### ISSUE TITLE
starting flatpak pulseeffects sets volume to maximum

### ISSUE THREAD

**Issue by pwr33** [wwmm/pulseeffects#638]
starting flatpak pulseeffects sets master volume to maximum
same is true with the packaged version in debian
I would think best thing is to leave pulseaudio master volume set as it was.

**Comment by wwmm** [comment]
There is no code in PulseEffects that would touch your sound card volume. We do not do that even for our virtual sinks. Either this is a bizarree bug in your Pulseaudio installation or a third party tool is doing that.

**Comment by wwmm** [comment]
Do you have `flat-volumes = yes` in your Pulseaudio configuration file? This could be the cause. At least Arch Linux disables it by default and I think that the next Pulseaudio release will also disable it.

**Comment by wwmm** [comment]
Enabling flat-volumes is a problem because it sets the sound card volume to the same level used by the playback stream with the highest volume. And our playback stream volume is set to 100 %. In my opinion it does not make sense to let the user mess with our playback stream. And we already have lots of parameters that have to be configured. As long as flat-volumes is not enabled in Pulseaudio setting our playback stream volume to 100 % does no harm.

In my opinion flat-volumes should never have been added to Pulseaudio. Outside of the corner case for which is was intended it only causes headaches.

**Comment by pwr33** [comment]
Excellent, that was the problem, Thanks!

sudo nano /etc/pulse/daemon.conf 
flat-volumes = no
pulseaudio -k
pulseaudio --start

Nice software!
