### ISSUE TITLE
4.7.1 broken equalizer

### ISSUE THREAD

**Issue by Vascom** [wwmm/pulseeffects#646]
In Fedora after updating to 4.7.1 stop working equalizer plugin. All settings available but no effect.
https://bugzilla.redhat.com/show_bug.cgi?id=1819739

Can you help? What plugin lib used for equalizer functional?

**Comment by wwmm** [comment]
Running PE in debug mode will show if lsp is the problem.

**Comment by wwmm** [comment]
Which Linux Studio Plugins version is being used?

**Comment by wwmm** [comment]
From Linux Studio Plugins `1.1.14` onwards you need PE `4.7.2`. This was the main reason why `4.7.2` was released.

**Comment by Vascom** [comment]
Oh, used lsp-plugins 1.1.15.

**Comment by wwmm** [comment]
If I am not mistaken LSP had to make a few API changes in order to better follow the LV2 standard.

**Comment by Vascom** [comment]
With lsp-plugins 1.1.13 problem still persist.

**Comment by wwmm** [comment]
In this case we will have to see the logs. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. THen play something. We should be able to see what is wrong.

**Comment by Vascom** [comment]
Start log with debug https://paste.centos.org/view/44f01661
Also I run music and disable/enable equalizer.

**Comment by wwmm** [comment]
That is weird `g_object_set_is_valid_property: object class 'lsp-plug-in-plugins-lv2-compressor-stereo' has no property named 'bypass'` This error is caused by the reasons I told above. Recent lsp versions do not have the `bypass` property anymore.

It is almost like the downgrade had no effect. Could it be that something from the previous verion is still there? lsp `1.1.13` worked fine and according to lsp changelog the property change was made in `1.1.14` https://lsp-plug.in/?page=news

**Comment by Vascom** [comment]
Not all packages downgraded :)
Now OK.
