### ISSUE TITLE
Issue with bluetooth headset no source

### ISSUE THREAD

**Issue by gayanper** [wwmm/pulseeffects#650]
I have a MIniso Bluetooth headset which requires the offset of 
pactl set-port-latency-offset bluez_card.FB_27_D8_84_41_52 headset-output 150000

When i enable pulseeffect i don't hear sound.

But if i set to 
pactl set-port-latency-offset bluez_card.FB_27_D8_84_41_52 headset-output 80000

I do hear sound with pulseeffect but the video is out of sync in youtube.

**Comment by wwmm** [comment]
I almost never use bluetooth devices but I noticed that they are very sensitive to the buffer size. What happens if you do not set the port latency through `pactl` and just play with the buffer sizes in PulseEffects settings menu?
![Screenshot from 2020-04-11 14-28-59](https://user-images.githubusercontent.com/16225172/79050545-15c0f480-7c01-11ea-8226-fc0222d97b39.png)

The out of sync problem may be caused by a high buffer value combined with the additional latency you are setting the port.

**Comment by gayanper** [comment]
It didn't helped sill the sound is behind the video, what should i do to make the sound runs faster ?

**Comment by gayanper** [comment]
I think i will have to skip the pulseeffect for all videos

**Comment by wwmm** [comment]
It is not a matter of running "faster". Somewhere there is a latency that GStreamer or Pulseaudio is not aware of and as a result is not being compensated. Does this problem only happen when using bluetooth?

**Comment by wwmm** [comment]
Which latency value does PE report in its title bar?

**Comment by gayanper** [comment]
Yes its only when using bluetooth headset. The title bar reports 90 ~ 100ms delay

**Comment by wwmm** [comment]
This sounds like a problem in Pulseaudio. From PulseEffects or GStreamer point of view there is no difference between a standard output and bluetooth. Pulseaudio exposes any output device in the same way. Maybe when it comes to latency there is something that Pulseaudio does when dealing with standard outputs that is not being done for bluetooth devices.

**Comment by Digitalone1** [comment]
Can you post a document that explains why this device requires 150k latency offset? 

Anyway, as far as I remember, Pulseaudio skips Alsa when playing with Bluetooth headsets. So there should be something in Pulseaudio that triggers the issue.

**Comment by gayanper** [comment]
i got it from https://askubuntu.com/questions/145935/get-rid-of-0-5s-latency-when-playing-audio-over-bluetooth-with-a2dp. Then i had to tweak the value until i got my bluetooth headset properly synched. 150K was the value that worked for me.

**Comment by Digitalone1** [comment]
> i got it from https://askubuntu.com/questions/145935/get-rid-of-0-5s-latency-when-playing-audio-over-bluetooth-with-a2dp. Then i had to tweak the value until i got my bluetooth headset properly synched. 150K was the value that worked for me.

That's very odd. So you get a delay from the beginning. Then you set a latency offset in pactl, which should get and extra delay in theory, but you have a/v synchronization.

Then you introduce PulseEffects, but the delay is back. I don't know, maybe it a matter to pick the right value when PulseEffects is running, but this seems more like an issue related to the device, PulseAudio or the bluetooth module rather than PulseEffects.

Did you try also other recommendations? Like the resynchronization switching the profile with a bash script? Or setting the video delay offset into the player?

**Comment by gayanper** [comment]
No i didn't try other recommendations since this is a problem when watching streaming services as well. So i think we can close this issue since its not a pulse effect issue.

**Comment by wwmm** [comment]
I do not know the details about how GStreamer and Pulseaudio interact to compensate the pipeline latency. But I noticed some time ago that GStreamer adds the Pulseaudio's sink latency in its pipeline latency calculation. The one we show in the title bar. I also noticed that if I add latency to the pipeline and do not notify GStreamer about it audio and video are not in sync anymore. So here comes what I think it is happening. This bluetooth device seems to need more latency than usual to work. And this additional latency is not being reported by Pulseaudio when GStreamer asks for the sink latency.

But as I said I am a little out of my league in this topic. This is something that a Pulseaudio or GStreamer developer would have more knowledge to talk about.

**Comment by wwmm** [comment]
I may not be far from the truth. Take a look at Pulseaudio 12 release notes https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/12.0/
```
When playing videos, it's important that the audio latency is known so that the video can be synchronized accurately. PulseAudio doesn't get good latency information from the kernel with A2DP playback, which has caused A/V sync problems for many people when watching videos. Now PulseAudio makes the audio buffer in the kernel much smaller, which reduces the problem a lot.
```
As far as I could understand they did not really solved the problem but made it less likely to be noticed. But as PulseEffects will add more latency on top of it the problem will come back.
