### ISSUE TITLE
Better application icon

### ISSUE THREAD

**Issue by wwmm** [wwmm/pulseeffects#73]
Now that PulseEffects is more mature and popular I think it would be nice to have a better application icon. I did the current one but I am by no means an graphic designer. There are probably guidelines for icon design and I didn't follow any. If there is anyone out there that can do a better icon feel free to do so :-)

**Comment by AsavarTzeth** [comment]
I am no expert but I do find it fun to make SVG icons in Inkscape. Although I am sure there are much more qualified people out there I could give it a shot. Do you have any ideas or preferences?

I actually like the idea of the current base motif. Perhaps one could stick with that and simply spice it up a bit and maybe put some musical note or something else that represents sound in there?

From what I read the most important aspect of an icon will always be to convey what the application does.

If you want a reference I made the icon for [Gydl](https://github.com/JannikHv/gydl/blob/master/data/gydl.svg).

**Comment by wwmm** [comment]
I agree that the icon should represent what the application does and that was what I tried to do. I also agree that improving the current icon is enough. There is no need to do something completely different.

What I would like to do but is beyond my capabilities is to make this icon more similar to the controls of a hardware equalizer. Something like was done in this icon [example](https://cdn.dribbble.com/users/4737/screenshots/1143924/equalizer_1x.png). The concept is the same but you immediately think about the controls of a hardware equalizer when you see it. For some reason the icon I did makes me think more about a scatter plot than an equalizer. Maybe it is because I am a physicist and I see plots all the time... But in any case the current concept could definitely be improved.

**Comment by AsavarTzeth** [comment]
I should be able to make something similar to that. Maybe not as quickly as one with more experience, but still.

I am guessing we are sticking with the same base colour's?


Wellington Wallace <notifications@github.com> skrev: (16 september 2017 17:43:51 CEST)
>I agree that the icon should represent what the application does and
>that was what I tried to do. I also agree that improving the current
>icon is enough. There is no need to do something completely different.
>
>What I would like to do but is beyond my capabilities is to make this
>icon more similar to the controls of a hardware equalizer. Something
>like was done in this icon
>[example](https://cdn.dribbble.com/users/4737/screenshots/1143924/equalizer_1x.png).
>The concept is the same but you immediately think about the controls of
>a hardware equalizer when you see it. For some reason the icon I did
>makes me think more about a scatter plot than an equalizer. Maybe it is
>because I am a physicist and I see plots all the time... But in any
>case the current concept could definitely be improved.  
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/wwmm/pulseeffects/issues/73#issuecomment-329976243

-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by wwmm** [comment]
Feel free to change the colors. I do not have any reason to keep the current ones.

**Comment by jeffshee** [comment]
How about some icons from this site?
https://www.flaticon.com/free-icon/mixer_535172#term=equalizer&page=1&position=37
Free to use as long as proper attributions are given.

**Comment by wwmm** [comment]
I didn't know about this site. Thanks!

I see no problems in giving the proper attributions. Did you get time to work on an icon @AsavarTzeth ? If you are working on it I will wait till you finish it. In case you did not have time I can choose an icon from this site.  They are decent.

**Comment by AsavarTzeth** [comment]
I did have time to start working on it, but then I got busy with my RHCSA certification studies. A slight miss-judgment of available time on my part.

There isn't really anything stopping me from working on it this weekend. I am actually quite fond of my current design ideas, which is why I have not given up on it.

If you are not in too much of a hurry I would like to try and finish my work. But if I have not finished it some time soon it is nice to know we have a fallback.

**Comment by wwmm** [comment]
There is no hurry. Take as much time as necessary to finish it.

**Comment by AsavarTzeth** [comment]
Okay I managed find some time to work on this recently. The icon still needs a lot of polish and adjustments, but it is at least possible to see the general idea behind it.

I am also personally happy with the choices of color, but I would of course be happy with feedback on this.

You can find the file on my [Google Drive](https://drive.google.com/open?id=0B-h3a-5Q8TgONklOamotTmlLR1U). The preview is awful, so download it and view locally.

So, what do you think so far?

**Comment by wwmm** [comment]
I like it :-). It is way better than the one we have now.

**Comment by AsavarTzeth** [comment]
Today I made some tests on how well it scales. As I expected, I tend to make objects too small, making details tiny when you scale down.

In order to fix this I had to increase the size of objects. In order to make room for this I decided to use 3 bars and buttons instead of 4. Originally I tried to keep the four bars because I felt it made it stand out a bit. Turns out there are good reasons most similar icons use 3.

I have uploaded the revised icon to my [Google Drive](https://drive.google.com/file/d/1pV82sOycOlyzeWa-6fuWTl8z7vIg2KfJ/view?usp=sharing), as before (again, browser preview is bad).

If everything looks good to you, I would be happy to make a pull request.

**Comment by wwmm** [comment]
Hi! I did some tests here and based on the attached snapshots I would only suggest brighter colors. I really liked the idea of blending the controls with an audio spectrum but unless we see the icon at larger sizes, like the image showing app search in gnome, we miss all the hard work you put on the details. Maybe it will be easier to appreciate the spectrum with a brighter background.

As you can see in the images it could also help to see the icon borders over a dock with dark background like the one in the standard gnome theme. Of course this may change with user theme. But I think that a brighter background will make this icon look good in any theme and not only the brighter ones.

These are the only issues I saw. Good work! :-)

![screenshot from 2017-11-19 16-27-26](https://user-images.githubusercontent.com/16225172/32993966-61c15b4c-cd47-11e7-89b6-51e94b65fa3d.png)
![screenshot from 2017-11-19 16-23-45](https://user-images.githubusercontent.com/16225172/32993967-61e31a70-cd47-11e7-8dac-00fb689ba7ad.png)
![screenshot from 2017-11-19 16-22-43](https://user-images.githubusercontent.com/16225172/32993968-620142ca-cd47-11e7-876a-cc6817d7a174.png)

**Comment by AsavarTzeth** [comment]
Those are some good and valid points. Anything that helps to show the details is a good idea in my opinion.

Initially I think I made the background darker to avoid it being too much grey. Also since I made the buttons white (or close enough), I could not make it too bright. However I will see if I can find a good middle ground.

**Comment by JackHack96** [comment]
Hey @wwmm have you seen the nice icon that team Papirus have created? [https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1116](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1116)
![screenshot from 2018-02-07 12-25-25](https://user-images.githubusercontent.com/3611330/35914010-fff7b344-0c01-11e8-96e5-25e016b36b7e.png)

**Comment by wwmm** [comment]
I didn't know about it. Nice icon! :-)

**Comment by servimo** [comment]
Nice icon

**Comment by zencubic** [comment]
@flipwise Yeah, but I  forked this from the [AlsaMixer](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/1f085c5c1e420a9b88b04260b7a8f7d7ab78a37f/apps/scalable/alsamixer-gui.svg) icon, so the pulseeffect icon I made in the La Capitaine Icon Theme is not unique. @wwmm If you want, I can create a unique icon for pulseeffects in the same style like [this](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/5017ec582da073f8872b7fc3c03856d9854f0390/apps/scalable/pulseeffects.svg) (Maybe with other colors :smile:)

**Comment by wwmm** [comment]
Feel free to do it @zencubic :-) There is no need to keep the current colors

**Comment by AsavarTzeth** [comment]
Well since you asked for it, here is my opinion.

Remembering some rules I learnt about icon design, I see some issues, mainly with the text version.

- It should visually relay what the application is or does.
- It should not be redundant to the title/name.
- Including text is generally contradictive to the role of an icon.

If anything I was hoping a new icon would somehow include more information, but not so much that it looks cluttered.

Perhaps it could be clearer by somehow visualizing sound; maybe make it look like it is moving from some sound/beat (think speaker).

As a starting point I like it though. Good choice of colors and it indeed seems unique enough.

**Comment by wwmm** [comment]
I like both icons but I am more inclined to the second because it makes me remember a [wave packet](https://www.google.com.br/search?q=wave+packet&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjC1tWDtqvcAhWF1lMKHTG4ASAQ_AUICigB&biw=1967&bih=753) :D But like most physicist I think it would look better if it were symmetric (without the first line from left to right).

At least to me both icons seem unique. And I like the choice of colors and gradient too.

**Comment by zencubic** [comment]
@wwmm So after your feedback I will drop the idea with the text and will focus on the "wave" icon.
@AsavarTzeth do you mean with the speaker something like this?
![](http://krucifixproductions.com/wp-content/uploads/2016/04/sound.png)
What I wanted to say is that I don't want to put too many details into the icon, because it can appear very small, especially in desktop environments. I also wonder how to delimit the PulseEffects icon from music players, because they might look similar. Do you have any ideas on how best to do this?

**Comment by AsavarTzeth** [comment]
I know, it is a tricky icon to add more to. I tried as you can see in earlier posts. My problem was scaling it down.

What I was thinking was subtle rings within the circle. When I said speaker i meant from the front, like the Rhythmbox icon.

Now though, I am thinking @wwmm may be having a better idea with the wave packet. Maybe just make it symetric and add some horizontal (still tilted) lines on each side?

**Comment by wwmm** [comment]
I don't know if it is possible to do at small sizes but something that would make the icon distinct from the ones in other audio apps is using a [water ripple](https://www.google.com.br/search?biw=2164&bih=828&tbm=isch&sa=1&ei=os1QW5rAINDv5gKst6-4Aw&q=water+ripple+&oq=water+ripple+&gs_l=img.3..0l10.252831.252831.0.253046.1.1.0.0.0.0.205.205.2-1.1.0....0...1c.1.64.img..0.1.203....0.kqcoHjYP-Wo). This came to my mind after looking at this  [Rhythmbox icon](https://upload.wikimedia.org/wikipedia/commons/0/08/Rhythmbox_Faenza.svg) from faenza.

Of course we can stick to your second icon concept if doing a water ripple is an impossible task.

**Comment by zencubic** [comment]
@wwmm @AsavarTzeth I tried a lot of different things to realize your ideas but none of them looked satisfying (I tried about 7 different approaches)
So I was working on the wave packet idea:
![pe-new_thesecondpng](https://user-images.githubusercontent.com/27775731/42999006-836e0184-8c1c-11e8-8acd-c69d8767dfee.png)
But I have the feeling that something doesn't look quite right. :thinking:

**Comment by wwmm** [comment]
It seems that replicating a wave packet with separated lines is not as easy as I thought it would be. Maybe if you reduce the size of the 3 lines at the center while keeping the size of the others it will look more like a packet.

I think it is looking more like a square because we do not have a continuous line to guide the eyes like in the plot of wave packets in the link I posted.

**Comment by zencubic** [comment]
So I tried a lot with the wave packet but it just didn't fit on smaller sizes. Now I have taken a new approach (a more conventional one :sweat_smile: ) and this has come out:
![pe-new svg](https://user-images.githubusercontent.com/27775731/43641554-7055bab6-9724-11e8-9774-b2f7d3f1687f.png)

**Comment by wwmm** [comment]
I like it :-) Is it finished?

**Comment by zencubic** [comment]
I think most of it's done. If you want to use it then only some fine work.

**Comment by wwmm** [comment]
Yes. Let me know when the fine work is done :-)

GTK about window has a section for artists that contributed to the project. With which name do you want to be mentioned there?

**Comment by zencubic** [comment]
So now it should be ready. I thought that the icon could be introduced as 2000. commit. :smile: (Because you are 3 commits away) If you're okay with it I will open a pull request that will update the icons (I found 2 icons, is the number correct?)
Preview of the (hopefully) final icon:
![pe-new svg](https://user-images.githubusercontent.com/27775731/43664173-4406e348-976c-11e8-93a1-a0d022ec9c1b.png)

**Comment by zencubic** [comment]
And for the name you can take simply ZenCubic

**Comment by wwmm** [comment]
You can do the pull request :-)

Yes there are two icons. One is shown only in the about menu and must have a smaller size
![screenshot from 2018-08-03 19-53-45](https://user-images.githubusercontent.com/16225172/43669034-a49f4ed6-9756-11e8-89fc-14b9addd1e42.png)
Honestly I don't know which size is recommended to the about icon. I just reduced till it seemed small enough
