### ISSUE TITLE
KDE Neon... strange routing

### ISSUE THREAD

**Issue by wd5gnr** [wwmm/pulseeffects#8]
This looks great. At first I didn't think it worked and then I figured out the routing is odd. If I route sound output to pulseeffects it goes nowhere. No traces on your display. However, I noticed that at some point I could get feedback. You have a record stream going and it only picks up from the record stream.

As a hack, I record the monitor of pulse effects

So my working config is:
(Playback)
Music Player -> Pulse Effects
pulseEffects -> Sound card

(Recording)
Monitor of PulseEffects -> PulseEffects

Putting the recording to any other source or muting it stops all output.

Not sure if I am double processing or not. Looks really good.

**Comment by wwmm** [comment]
Hi

PulseEffects creates a null pulseaudio sink and then "records" any audio sent to it. When the application switch is set to on the application is moved from its current sink(usually the sound card) to PulseEffects null sink. It seams to me your configuration is fine. But in order to be sure I am posting here snapshots of my pavucontrol window so you can compare:

![screenshot from 2017-04-30 14-55-11](https://cloud.githubusercontent.com/assets/16225172/25566713/4f43f81c-2db5-11e7-999b-ac42957f5caf.png)
![screenshot from 2017-04-30 14-55-15](https://cloud.githubusercontent.com/assets/16225172/25566715/56e3f9fa-2db5-11e7-9af0-c7decdc8d351.png)

**Comment by wwmm** [comment]
By the way what you did in order to get PulseEffects working should have happened automatically.

**Comment by wd5gnr** [comment]
Ok, that is how I am configured, but I don't think it happened automatically. Perhaps I fat fingered something. At first, it seemed to have no effect then I realized that there was no source feeding the eq. But it was displaying the playing audio just not filtering it. Then I looked at the recording thing and somehow got into a horrible feedback situation. So after that I was just experimenting and stumbled onto those settings.
