### ISSUE TITLE
How to create .deb package?

### ISSUE THREAD

**Issue by ForumLiker** [wwmm/pulseeffects#81]

**Comment by wwmm** [comment]
I only know how to build packages for Arch Linux. But now that PulseEffects is using meson I think that any tutorial you can find about how to build .deb of programs that use meson should be a good starting point.

**Comment by AsavarTzeth** [comment]
See Debian documentation, here are some links that could help get you started:
- https://wiki.debian.org/Packaging
- https://www.debian.org/doc/manuals/maint-guide/

Since this is not a PulseEffects issue it should be closed. Unless what you really meant, was a request for a deb package?

If you need information about how to build PulseEffects as part of the packaging process see the [wiki](https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source). Documentation about the build system can be found [here](http://mesonbuild.com/).

Did I miss anything? In that case you would need to be more specific.

**Comment by ForumLiker** [comment]
I did not find. I need to assemble PulseEffects in a deb package.

**Comment by wwmm** [comment]
Closed as it is not a PulseEffects issue
