### ISSUE TITLE
Convolver!  Wow

### ISSUE THREAD

**Issue by jawz101** [wwmm/pulseeffects#815]
I had never looked into Linux sound effects stulff until tonight and stumbled across PulseEffects, then clicked around and found there was a convolver.  Then found it supports the Impulse Response Samples that Viper4Android supports.  Now, that I have played with some.  I just wanted to throw a recommendation for my favorite IRS profiles from V4A

IRS TubeAmplifier And Technics Preamplifier - 
https://forum.xda-developers.com/showpost.php?p=40247380&postcount=560

At least on my phone earbuds and headphones any one of these profiles instantly makes music sound so much warmer.  I'm not an audiophile but every time I read something sounds "warm" this is what I think of.  Can these profiles be added as default built-in profiles?  I think it would really show off this feature because it's the only effect I ever use.
[IRS_TubeAmplifier_And_Technics_Preamplifier__).zip](https://github.com/wwmm/pulseeffects/files/5504296/IRS_TubeAmplifier_And_Technics_Preamplifier__.zip)

**Comment by jawz101** [comment]
and many are wav files but I cannot import those

**Comment by wwmm** [comment]
> I tried renaming one of the wav files from the tube amp zip download from here to an IRS filetype but that didn't import https://www.sjeng.org/foobar2000.html

At this moment only stereo impulse response files are supported. One workaround you could try to use those would be to use a program that converts them to stereo.

>Can these profiles be added as default built-in profiles

We do not offer any impulse file because they usually have copyrights. So it is a little dangerous to do this. If you want you can add a link to them in our wiki page https://github.com/wwmm/pulseeffects/wiki/Impulse-Responses.
