### ISSUE TITLE
"Import APO Presets" importing Q values wrong

### ISSUE THREAD

**Issue by pulpan977** [wwmm/pulseeffects#844]
I tried to import some Parametric EQ presets (from AutoEQ repository https://github.com/jaakkopasanen/AutoEq) and it seems the Q values are either rounded or the decimals are just dropped. This alters the sound as Q values such as 0.45 become 0, 6.45 becomes 6 etc. Then I have to correct the Q values manually.

**Comment by Digitalone1** [comment]
Hello. I think this is more an issue related to GTK localization rather than the import feature of PulseEffects. The same behaviour was happening with GTK glade app which I had to run with `LC_ALL=C` to save float values correctly. 

Which are your operating system and PulseEffects version? Maybe this is fixed in the last GTK updates.
If don't, try to run PulseEffects with and `LC_ALL=C`, import and save the presets, then the values should be correct even if they are showed rounded.

**Comment by Digitalone1** [comment]
I found the reason. It's the system locale, but also our import feature is wrong.

http://www.cplusplus.com/reference/string/stof/

`Note that the format accepted by these functions depends on the current locale.`

Indeed, if I import [this](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/64%20Audio%20A18s%20(universal)/64%20Audio%20A18s%20(universal)%20ParametricEQ.txt) with `LC_ALL=C`, it works:

![Schermata del 2020-12-02 08-59-02](https://user-images.githubusercontent.com/25790525/100845100-fff88c00-347c-11eb-8819-2d1efb5e1d68.png)

So we should modify the import feature not relying on the system locale, maybe using something different from `std::stof`.

**Comment by Digitalone1** [comment]
When I have time, I'll try to make a pull request with [this](https://en.cppreference.com/w/cpp/utility/from_chars) not depending on the locale.

**Comment by Digitalone1** [comment]
Compiler on archlinux does not support the float conversion with from_chars. Stringstream should be used.
