### ISSUE TITLE
rnnoise not working 

### ISSUE THREAD

**Issue by Taza53** [wwmm/pulseeffects#901]
using manjaro kde stable. kernel 5.10.15-1

-pipewire is setup
-rnnoise is installed
then reinstall pulseeffects it did not work(not aur package)

tested on new virtual box (manjaro kde minimal)
setup pipewire
install rnnoise
install pulseeffects(not aur) and gst-plugin-pipewire
pulseeffets runs but still no rnnoise

_Originally posted by @Taza53 in https://github.com/wwmm/pulseeffects/issues/886#issuecomment-779863611_

**Comment by wwmm** [comment]
Probably because the package maintainer did not recompile PulseEffects with rnnoise installed in his/her computer. When you install from aur our source code will be compiled in your computer and it will see that rnnoise is there. But the package from the repository has already been compiled. Reinstalling it changes nothing. You have to report this to Manjaro package maintainers.

**Comment by Taza53** [comment]
Thank you will test aur it and report it

**Comment by Taza53** [comment]
the aur version works
