### ISSUE TITLE
Effects not active on startup, despite appearing enabled

### ISSUE THREAD

**Issue by eiglow** [wwmm/pulseeffects#903]
I am on Fedora 34 with Pipewire.

For me, when starting Pulseeffects, the Limiter and Equaliser voice effects appear enabled, but are actually not. To get them to work, I have to un-check and then check their boxes again, and then they work. Can anyone else reproduce this behaviour?

**Comment by wwmm** [comment]
That bu I did not see yet. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Try to get logs in a situation when we can see what is printed when things are not working and what happens after changing the checkbox state so it works.

**Comment by eiglow** [comment]
[pulseeffects.log](https://github.com/wwmm/pulseeffects/files/6022899/pulseeffects.log)

This is the log from opening pulseffects, switching to the inputs screen (microphone icon on top left), un-checking and re-checking the Limiter effect, doing the same to the Equalizer effect, and then closing the app.

**Comment by wwmm** [comment]
The only thing unusual I see in your logs are the 2 rounds of `presets_manager` lines about possible presets path. There should be only one block at the beginning. Strange... 

As far as I could see the mic pipeline was already active by the time you used each plugin checkbox. And when you disabled there was a message in the logs saying that they were already disabled. It is almost like we are having problems with the gsettings database and the button configuration is not propagating to the interface. I wonder if it is one of those situations where the package should be recompiled after one of the system libraries are updated.

**Comment by Kneemund** [comment]
I had the same issue on Arch using the legacy PulseAudio version from the AUR. Recompiling the package fixed it.

**Comment by wwmm** [comment]
I wonder if this issue is somehow related to #923. Today I had to release new versions both for PipeWire and Pulseaudio. IT seems something changed in dconf `0.40`.

**Comment by azsorlex** [comment]
@eiglow @wwmm I also have this issue. I very recently reinstalled my system (EndeavourOS), and the exact same problem occurs for me. I didn't have this issue before my reinstall, and I was already using pipewire back then.
The way I get around this problem is by opening PE, loading a "default" profile that has everything disabled, and then re-loading my custom profile with all of the effects.
Here is my log: [pulseeffects.log](https://github.com/wwmm/pulseeffects/files/6153107/pulseeffects.log). I opened PE, switched to the default profile, switched back to my profile (named Fidelio.json), then quit PE. I noticed something strange in the log: when I load the default profile, it says "[effect] is already disabled" for all four effects that I use, and then when re-loading my profile, it says "[effect] is enabled", which aligns up with the behaviour of the problem.

**Comment by wwmm** [comment]
@azsorlex do you have dconf `0.40` installed. This dconf version will need PulseEffects `5.0.2` in PipeWire and `4.8.5` in Pulseaudio.

**Comment by azsorlex** [comment]
@wwmm Yes. Do I also need PE 5.0.2? The packages appear to be out of date on both the main Arch repo and the AUR.

**Comment by azsorlex** [comment]
Ok it's just the displayed version. The AUR version is 5.0.2. About to reboot and see if the problem is fixed.

**Comment by azsorlex** [comment]
@wwmm Yep 5.0.2 fixed it.

**Comment by cziss** [comment]
Hi, I have exactly same problem. I'm running on pulseeffects-legacy. I was able to "solve" problem with downgrading to dconf-0.38.0-1. So, there must be some problem with dconf-0.40

**Comment by wwmm** [comment]
@cziss I released an update to the legacy branch too. As far as I am aware `4.8.5` is compatible with dconf `0.40`

**Comment by cziss** [comment]
> @cziss I released an update to the legacy branch too. As far as I am aware `4.8.5` is compatible with dconf `0.40`

OK, thx for info. It's seems not updated in AUR right now.

**Comment by eiglow** [comment]
I think this issue can be closed now, on pulseeffects 5.0.3 and dconf 0.40 I don't experience it anymore.
