### ISSUE TITLE
Can't exit when run with --no-window

### ISSUE THREAD

**Issue by zestyr** [wwmm/pulseeffects#96]
When running from the terminal with --no-window, I can't Ctrl-C to stop it. 
I get the following error:
```
Traceback (most recent call last):
  File "PulseEffects/effects_base.py", line 336, in on_message_element
    def on_message_element(self, bus, msg):
KeyboardInterrupt
```

**Comment by wwmm** [comment]
This is not going to work. The `--no-window` option does not turn PulseEffects in a daemon. It is just not showing the window. Everything else related to the graphical interface is still loaded and running.

In order to close PulseEffects in this scenario you have to run its executable again. At startup it will detect that there is already an instance running and it will only show its window. Then you can close as usual.
